### ISSUE TITLE
Support prompt=create

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1029]
https://openid.net/specs/openid-connect-prompt-create-1_0.html

**Comment by leastprivilege** [comment]
https://www.strathweb.com/2022/09/initiating-user-registration-via-openid-connect-with-duende-identity-server/

**Comment by filipw** [comment]
Please support!

**Comment by AndersAbel** [comment]
This looks like a dupe of #432

**Comment by brockallen** [comment]
Yes, dup of: https://github.com/DuendeSoftware/IdentityServer/issues/432
