### ISSUE TITLE
Consider removing all old/consumed entries in the grant store when refresh tokens is revoked

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1065]
Given that we mark renewed refresh tokens with a consumed time, it might make sense when the current refresh token is revoked that we do an actual delete on all the prior/consumed entries in the grants table. We'd need to do this by client_id/sid combo, so we'd need the DefaultRefreshTokenStore to first load the record, get the info, and then use RemoveAllAsync on the IPersistedGrantStore.

Related: https://github.com/DuendeSoftware/IdentityServer/issues/1061

**Comment by josephdecock** [comment]
I think that the new `DeleteOneTimeOnlyRefreshTokensOnUse` flag added in #1105 addresses this - the approach is a little different, but if the goal is to prevent build up of consumed grants, that flag will do the job. Cleaning up existing consumed grants would also be a good thing to do, which can be accomplished by enabling the cleanup job and enabling cleanup of consumed tokens in the cleanup job. Both of those config flags default to off right now. My thinking so far has been that we should eventually change the defaults of both, but probably do that as part of the 7.0 release. My main concern is for people who are using the consumed records for auditing, etc. My feeling is that a potentially destructive change in default behavior belongs in a major release.

**Comment by josephdecock** [comment]
The other default change we should probably make is to default to re-usable refresh tokens. Or perhaps, we could do something cool like intelligently default to one-time use tokens only if the client doesn't have a secret?

**Comment by josephdecock** [comment]
See https://github.com/DuendeSoftware/IdentityServer/issues/1128

**Comment by brockallen** [comment]
> I think that the new DeleteOneTimeOnlyRefreshTokensOnUse flag added in https://github.com/DuendeSoftware/IdentityServer/pull/1105 addresses this

Are you sure? If the customer still has one-time RTs and does not set DeleteOneTimeOnlyRefreshTokensOnUse, they still have several RTs in the DB for the logic session, right? Then the user logs out of the client and that does revocation of the RT, then all those consumed RTs should be removed.

**Comment by josephdecock** [comment]
The way I'm thinking about this is, why would you configure DeleteOneTimeOnlyRefreshTokensOnUse to false? I'm thinking it is to detect replay attacks or for some kind of auditing. You probably still want to do that even after a token is revoked, so you probably don't want to delete the consumed tokens on logout when DeleteOneTimeOnlyRefreshTokensOnUse. 

But now that I write that down, there's no reason we couldn't do both what you say, and also respect the new flag in that logic. 

IOW, I think what we should do is this: when a token is revoked AND DeleteOneTimeOnlyRefreshTokensOnUse is true, delete the consumed tokens.

**Comment by brockallen** [comment]
> The way I'm thinking about this is, why would you configure DeleteOneTimeOnlyRefreshTokensOnUse to false?

Yes, it's to do replay detection to detect attackers with stolen RTs, and then give yourself a chance to revoke them all (as per some of the recent specs). That's the point of us having the ConsumedTime -- keeps the record in the DB to know it was already used. But once it's revoked, then you don't need those old records anymore for detecting this attack.

**Comment by josephdecock** [comment]
I agree that there isn't anything to do with the tokens once they've been revoked, but maybe you want to monitor how often you're being attacked, or try to track patterns in your attacker's behavior.
