### ISSUE TITLE
Introspection Endpoint not working for resources in URI format

### ISSUE THREAD

**Issue by andrewclymer** [DuendeSoftware/IdentityServer#1080]
In IdentityServer, the resource indicator validation requires the resource indicator to be in a URL format. 

Suppose we create a resource that complies with that format. In that case, this causes an issue when attempting to authorize against the Introspection endpoint, as the basic authentication username contains a colon, and the parser can't read the resource name and, therefore, always returns 401.

example 
Authorization header - Basic dXJuOnJlc291cmNleDpzZWNyZXQ=
Decoded value- urn:resource:secret

Do you know if this is a known issue? Is there a workaround?

**Comment by brockallen** [comment]
I'm assuming it works if the credentials are sent in the post body?

**Comment by andrewclymer** [comment]
Thanks, Brock, I can't find any examples of placing authentication credentials in the body, can you point me the right direction? Thanks Andy

**Comment by brockallen** [comment]
The creds can be passed that way for the token endpoint. I am assuming we accept them in a similar way for introspection, but it might not be allowed in the spec. I'd have to check for certain.

**Comment by brockallen** [comment]
Anyway, the value you have above decodes to "urn:resourcex:secret". I don't think that's the OAuth basic auth encoding. You'd have to first URL encode the value to "urn%3Aresourcex" then concat w/ the secret, and then base64 encode.

https://www.rfc-editor.org/rfc/rfc6749.html#section-2.3.1

**Comment by josephdecock** [comment]
You could take a look at the IdentityModel library for some examples. It has an option to set the credentials in the post body or the authentication header, and it also does the url and base 64 encoding.

**Comment by andrewclymer** [comment]
Perfect thank you
