### ISSUE TITLE
Feature: "Resource Isolation"

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#11]
Current proposal - add `Isolated` flag on `ApiResource`.

https://tools.ietf.org/html/rfc8707

**Comment by brockallen** [comment]
Motivations:

    resource specific token processing, e.g. encryption or resource specific claims
    prohibit of reuse or token at resource, e.g. don't allow API to call other API with same token. (i.e. APIs don't trust one another)
    prevent a single token from being too powerful, e.g. prevent leaked tokens that have too much access

**Comment by brockallen** [comment]
https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-08

this is our interpretation of how it works in IdentityServer

**a) no resource parameter, scope parameter**
* all resources requiring indicator are excluded
* AllowedScopes works as today
* same behavior as today + if scope is defined in multiple resources, then you'll get multiple audiences

**b) resource parameter, scope parameter**
* all resources that match the resource parameter(s) are used
* must use new AllowedResources config setting
* get one access token per resource with downscoped behavior
    * if a requested scope is not present in any resource -> invalid_target
    * if a requested scope is not present in one or more resource
        * if resource has no scopes defined -> access token without scopes
        * if resource has scopes defined -> invalid_target

**c) resource parameter, no scope**
* all resources that match the resource parameter(s) are used
* must use new AllowedResources config setting
* get one access token per resource with no scopes if resource has no scopes defined

**Comment by brockallen** [comment]
New config idea:
* Scopes top level
* ApiResource contains list of scope names (reference model, not ownership model)

Config: no resources, only scopes
Request: no resource, scope
* Aud is scope
* No introspection possible

Config: resources and scopes
Request: no resource, scope
* Aud is matching ApiResources
* Introspection based on ApiResource secret

Config: resources and scopes
Request: resource, no scope
* Aud is matching ApiResources
* Introspection based on ApiResource secret

Config: resources and scopes
Request: resource and scope
* Aud is matching ApiResources
* Introspection based on ApiResource secret

**Comment by brockallen** [comment]
Profile Service Options:
* call every time a new AT is requested
* call once per resource and cache results in RT in store

Also, there's the client flag "AlwaysUpdateClaimsOnRefresh"

**Comment by brockallen** [comment]
Should we allow ApiResources that aren't isolated if request contains scopes in those ApiResources, and the request contains resource params (think: authZ ep). 

IOW, the client wants a single request to authZ EP for scope1/non-isolated resource1, and scope2 in isolated resource2a and isolated resource 2b. We want 3 total ATs: 
* aud: resource1, scope: scope1
* aud: resource2a, scope: scope2
* aud: resource2b, scope: scope2

those would be 3 token EP requests, 2 with resource param, 1 without.

**Comment by brockallen** [comment]
Also, do we want to allow this in implicit flow?

**Comment by brockallen** [comment]
Also, we want to allow token EP to request resource to isolate AT even if that ApiResource is not marked as isolated.

**Comment by brockallen** [comment]
Need to track the original resource indicators on authZ ep and carry over to token EP to validate that no isolated resources beyond the original authZ request are emitted.
