### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1125]

**Comment by josephdecock** [comment]
One thing we'll need to address is the new time provider: https://github.com/dotnet/aspnetcore/pull/47717

**Comment by brockallen** [comment]
related: https://github.com/DuendeSoftware/IdentityServer/issues/1247

**Comment by leastprivilege** [comment]
We should bump the version of main to 7.0 alpha and add net8 target.

@josephdecock I can show you how that works if needed
