### ISSUE TITLE
Remove dependency on HttpContext from Server Side Session Cleanup Job

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1138]
The server side session cleanup job sometimes throws null reference exceptions (e.g. https://github.com/DuendeSoftware/Support/issues/420) when it tries to use `DefaultServerUrls.Origin`, which relies on the HttpContext:

```csharp
public string Origin
{
    get
    {
        var request = _httpContextAccessor.HttpContext.Request;
        return request.Scheme + "://" + request.Host.ToUriComponent();
    }
}
```

Related: https://github.com/DuendeSoftware/IdentityServer/issues/56

**Comment by brockallen** [comment]
It is using this when it tries to do back channel logout calls?

**Comment by brockallen** [comment]
Closing, as the fix in the PR addresses the exception.
