### ISSUE TITLE
Session Id claim is missing from identity token

### ISSUE THREAD

**Issue by Cephei** [DuendeSoftware/IdentityServer#1156]
We are using IS version 6.1.7 with server-side sessions enabled. Our product teams are looking to start implementing single-logout using backchannel, but I noticed our identity tokens do not contain the `sid` session identifier claim. I briefly checked the documentation and reviewed the IS code, but may have missed something. Is there an easy way to enable this claim to be issued? I see it would be filtered out by the custom profile service.

**Comment by brockallen** [comment]
6.2.3 was just released with this fix. Thanks all!
