### ISSUE TITLE
Backchannel Logout Token Issues

### ISSUE THREAD

**Issue by Cephei** [DuendeSoftware/IdentityServer#1169]
**Which version of Duende IdentityServer are you using?**
6.2.2

**Which version of .NET are you using?**
6

**Describe the bug**

1. Logout tokens do not use the recommended header type `logout+jwt`. It looks like IdentityServerTools may need to be refactored a bit to provide the token type for the `Token` class constructor. See: https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken
2. ~~It appears like our Logout Tokens are being signed properly with the private key, however, the Logout Token JWT algorithm shows it as a symmetric HS256. I believe this is causing validation to fail, however, perhaps I'm misunderstanding something. See the screenshot and below example token. The json/certificate in the screenshot comes directly from our Duende `jwks` endpoint.~~ **UPDATE:** Not a bug.

**Example JWT**
```
eyJhbGciOiJIUzI1NiIsImtpZCI6IjA3NkYxOThBNjhDQjVDN0ZGREFFOTY2QkY5MDcwMTFEIiwieDV0IjoiZE9aQW5qUHFRVnVXclZLbmluLS1HcTQzSkFZIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2FjY291bnRzLnFhLnNvbWVleGFtcGxlb3JnLm5ldCIsIm5iZiI6MTY3NTM2MjkxOSwiaWF0IjoxNjc1MzYyOTE5LCJleHAiOjE2NzUzNjMyMTksImF1ZCI6InRpbWUtbG9jYWwiLCJqdGkiOiIwNzI3QkFBNkJGMDJDREU1RkEyRTRDQTQ3Njc3MEIzNiIsImV2ZW50cyI6eyJodHRwOi8vc2NoZW1hcy5vcGVuaWQubmV0L2V2ZW50L2JhY2tjaGFubmVsLWxvZ291dCI6e319LCJzdWIiOiI4NCIsInNpZCI6IjVBMkUxNURDRDI3RENFNTY4MTEwQjJEOTFFRjA0MTZCIn0.X0XZYFFZsehhjO0IuEceFEXsWN7uqF2TLmHhuBLhUeo
```
<img width="1245" alt="Screen Shot 2023-02-05 at 9 45 38 PM" src="https://user-images.githubusercontent.com/1054639/216873144-41d91bd4-0b8c-451c-8271-6409dbf03c2b.png">

**Comment by brockallen** [comment]
The `typ` problem still exists, yes?

**Comment by Cephei** [comment]
It does, but it's not a big problem for us really. For now, we'll configure our validation to allow both `at+jwt` and `logout+jwt`. I think Duende may wish to remove the `at+jwt` type since it's not an access token. Perhaps that could be considered a bug.

However, since `logout+jwt` is an RFC recommendation, we can perhaps view that as an enhancement.

**Comment by brockallen** [comment]
Well, of you look above we already have a PR for this. I'm thinking we'll target 6.3.0 for a fix, though, since it's a new option. Thoughts?
