### ISSUE TITLE
System.ArgumentOutOfRangeException in DynamicSchemeAuthenticationMiddleware

### ISSUE THREAD

**Issue by vitalyobukhov** [DuendeSoftware/IdentityServer#1171]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
net6.0

**Describe the bug**
`Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware`  throws  `System.ArgumentOutOfRangeException` in case if `/scheme` part was not provided within the URI of request.

**To Reproduce**
Just plug in the standard IdentityServer via `IdentityServerApplicationBuilderExtensions.UseIdentityServer` within the web app and try to access `/federation` path without trailing slash or scheme-specific suffix.

**Expected behavior**
No exception - avoid `context.Request.Path.Value.Substring(startIndex + 1)` if `startIndex >=  context.Request.Path.Value.Length`.

**Log output/exception with stacktrace**
```
System.ArgumentOutOfRangeException
startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
```

**Additional context**
Found it during ISEs 500 triage.

**Comment by brockallen** [comment]
PR submitted for this, @vitalyobukhov.
