### ISSUE TITLE
BasicAuthenticationSecretParser performs client secret length check before decoding it

### ISSUE THREAD

**Issue by t-mxcom** [DuendeSoftware/IdentityServer#1173]
Hello!

I ran into a similar problem as reported in [#654](https://github.com/DuendeSoftware/IdentityServer/issues/654) after I updated the `IdentityModel` NuGet-package in my application from 4.6.0 to 6.0.0.
I'm using a client secret that is much shorter than 100 characters but always received the `Client secret exceeds maximum length.` error after updating `IdentityModel`.

So I started some research and found out the following:

* The `IdentityModel` NuGet-package version 4.6.0 sent the client credentials as part of the request body while version 6.0.0 uses the `Authorization` header.
* This library concats client id and client secret, URL-encodes them and then performs a base64 encoding of the resulting string.
* When `Identity Server` receives the token request, it reads the `Authorization` header in the `BasicAuthenticationSecretParser` class.
* This class does the base64 decoding of the `Authorization` header value, and reads client id and client secret.

and here is the problem

* After reading client id and client secret, `BasicAuthenticationSecretParser` immediately performs the client secret length check on the still URL-encoded value which might be much longer than the decoded value!  
(File `BasicAuthenticationSecretParser.cs`, line 107)
* Currently, decoding of the client secret is done just a few lines later (line 116).

The line numbers mentioned above use the code version published at the time of writing this issue.

**Expected behavior**

The client secret length check should be done after decoding the client secret.

**Comment by brockallen** [comment]
@t-mxcom we've submitted a PR for this. Once I dig some more into this, I realized we were doing significant string parsing prior to any checks, so I tried to do some basic length checks on the incoming authorization header. Once that was done, then it was safe(r) to do the URL decoding and then exact length checks you were asking about.

Have a look, please.  Thanks
