### ISSUE TITLE
Expose the CSP script/style hashes

### ISSUE THREAD

**Issue by glucaci** [DuendeSoftware/IdentityServer#1183]
**Which version of Duende IdentityServer are you using?**
6.1.6

**Which version of .NET are you using?**
.NET 7

**Question**
Would it be possible to expose all the needed hashes for CSP? 
We are building a custom CSP policy and would be nice to can access the hashse for the `IdentityServer` content.

For example the [CheckSessionResult](https://github.com/DuendeSoftware/IdentityServer/blob/ffa4da997b44dcb32103bb26a919fb14cd1cf0f5/src/IdentityServer/Endpoints/Results/CheckSessionResult.cs#L47)

**Comment by mannawar** [comment]
Hi,
We can easily do that using CSP Http header. I would like to work on that.?
Is there anyone assigned

**Comment by josephdecock** [comment]
Thanks for the offers all, but that is not necessary - I am working on this one.
