### ISSUE TITLE
Consider adding cause to backchannel logout

### ISSUE THREAD

**Issue by gerardpeters** [DuendeSoftware/IdentityServer#1198]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
.NET 7
**Describe the bug**

Hi,
I'm implementing the backchannel logout with session expiration. It all works but I was looking for a way to get the cause of the backchannel logout.
I would like to get the reason in the client for logging out the user so I can show the login page or the loggedout page depending whether the session timed out or the user did logout himself.
Something like:
CLIENT_LOGOUT
SESSION_TERMINATION
SESSION_MAX_TIMEOUT

Where this will be added to the logout token. Is this possible?

**Comment by brockallen** [comment]
The spec does say that other values could be in the message.

**Comment by brockallen** [comment]
@gerardpeters We opened a PR for this. Please have a look and let us know if that would work for you.
