### ISSUE TITLE
Feature Request - OpenTelemetry Metrics

### ISSUE THREAD

**Issue by lemonlion** [DuendeSoftware/IdentityServer#1199]
It's great that OpenTelemetry Tracing in Identity Server is implemented, but is there any plan to create some OpenTelemetry metrics?  Would be invaluable to be able to then hook into those metrics in say Grafana via say the Prometheus exporter.

**Comment by brockallen** [comment]
I've moved this here for consideration. Thanks for the suggestion.

**Comment by leastprivilege** [comment]
Tracked here:

https://github.com/DuendeSoftware/IdentityServer/issues/1200#issuecomment-1450887403

**Comment by lemonlion** [comment]
> Tracked here:
> 
> #120

Do you mean #1200 ?

**Comment by leastprivilege** [comment]
yes ;)
