### ISSUE TITLE
Consider making ProtocolRoutePaths constants public

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1201]
> it would be helpful for us to have the ProtocolRoutePaths constants from the Constants.cs available in IdentityServerConstants.cs so we can refer to them.

**Comment by josephdecock** [comment]
This seems pretty straight-forward. Do we want this in 6.3? Should we back-port to 6.2 or earlier?

**Comment by brockallen** [comment]
6.3 would be fine, IMO
