### ISSUE TITLE
Use of DateTime.Utc in DefaultEventService prevents mocking of time

### ISSUE THREAD

**Issue by kimayoi72** [DuendeSoftware/IdentityServer#1203]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

.NET 6.0

**Describe the bug**

In version 6.0.4 I used to test time things, by mocking `ISystemClock` in my integration tests.
Implementation (6.0.4) of `DefaultEventService` used `evt.Timestamp = Clock.UtcNow.UtcDateTime` to set the timestamp of the event.
The new implementation uses `evt.Timestamp = DateTime.UtcNow;` which prevents mocking the time. 

The change was introduced in https://github.com/DuendeSoftware/IdentityServer/commit/f7381429e49ce4779b6e9128e2c08b1fdf5a82d9

**To Reproduce**

Use the following XUnit test and call it in 6.04 and 6.2.3.

```csharp
using System;
using Duende.IdentityServer.Configuration;
using Duende.IdentityServer.Events;
using Duende.IdentityServer.Services;
using Microsoft.AspNetCore.Http;
using Moq;
using Xunit;

public class DefaultEventServiceTests
{
    /// <summary>
    /// Checks, that <see cref="DefaultEventService"/> implementation uses the given
    /// <see cref="DefaultEventService.Clock"/> and not <see cref="DateTime.UtcNow"/>`.
    ///
    /// The problem is, that Duende uses <see cref="Microsoft.AspNetCore.Authentication.ISystemClock" /> which uses
    /// the implementation <see cref="Microsoft.AspNetCore.Authentication.SystemClock" /> which removes the milliseconds.
    ///
    /// Better to use <see cref="Microsoft.Extensions.Internal.ISystemClock" /> which uses <see cref="Microsoft.Extensions.Internal.SystemClock" />
    /// and returns <see cref="DateTimeOffset.UtcNow"/>.
    /// </summary>
    [Fact]
    public void Uses_own_Clock_instead_of_DateTime()
    {
        var fixedTime = new DateTime(2023, 01, 02, 03, 04, 05).ToUniversalTime();
        var clockMock = new Mock<Microsoft.AspNetCore.Authentication.ISystemClock>();
        clockMock.Setup(p => p.UtcNow).Returns(new DateTimeOffset(fixedTime, TimeSpan.Zero));

        // other stuff to mock due to access in RaiseAsync
        var connectionMock = new Mock<ConnectionInfo>();
        var contextMock = new Mock<HttpContext>();
        contextMock.Setup(p => p.Connection).Returns(connectionMock.Object);
        var contextAccessorMock = new Mock<IHttpContextAccessor>();
        contextAccessorMock.Setup(p => p.HttpContext).Returns(contextMock.Object);

        var sut = new DefaultEventService(
            new IdentityServerOptions { Events = new EventsOptions { RaiseSuccessEvents = true } },
            contextAccessorMock.Object,
            Mock.Of<IEventSink>(),
            clockMock.Object);

        var evt = new ClientAuthenticationSuccessEvent("clientId", "authMethod");
        sut.RaiseAsync(evt);

        Assert.Equal(fixedTime, evt.TimeStamp);
    }
}
```

Steps to reproduce the behavior.

- Execute the test with version 6.0.4 => test succeeds
- Execute the test with version 6.2.3 => test fails 

**Expected behavior**

Test is working in 6.2.3.

**Log output/exception with stacktrace**

None available.

**Additional context**

The problem is the usage of `Microsoft.AspNetCore.Authentication.ISystemClock` instead of `Microsoft.Extensions.Internal.ISystemClock`. The implementation of first interface removes milliseconds.
The implementation of second interface returns the time with milliseconds.

**Comment by aomader** [comment]
Do you have an ETA for a proper solution for that one?

**Comment by brockallen** [comment]
@aomader None right now -- we have a full plate for 6.3, but if we have time at the end we will go back over the list of these issues (the ones in "Future") and see if any can be completed within the current release schedule. Otherwise, it will be re-considered once we do our 7.0 planning.

**Comment by MiErnst** [comment]
Would love to get this fixed!

**Comment by josephdecock** [comment]
.NET 8 brings the new time provider abstraction as well, and 
it looks like it will be used by identity, etc. See https://github.com/dotnet/aspnetcore/pull/47717. I think we should consider using that abstraction.

**Comment by davidfowl** [comment]
The abstraction will work down level as well (netstandard 2.0).

**Comment by brockallen** [comment]
Moving to 7.0 milestone for consideration.
