### ISSUE TITLE
Mark properties as required

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1247]
Many not-null properties are initialized `=default!`. Consider changing those properties to be required instead, once we drop support for to .NET 6.0.

**Comment by brockallen** [comment]
If we must still support .NET 6, etc, in out 7.0 release then we might need to push this to Future.

**Comment by josephdecock** [comment]
I'm having second thoughts on this, since this would probably introduce breaking changes.
