### ISSUE TITLE
Consider flag to disable DPoP

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1266]
https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/265#discussion_r1184354552

**Comment by leastprivilege** [comment]
I think I would prefer to fail if a proof token is received and not the right license...

**Comment by brockallen** [comment]
Something to consider -- if there is no license, should we still emit a log entry indicating that this is a licensed feature? I'm thinking the scenarios where a customer is evaluating or in dev mode and don't know it's a higher level feature.

**Comment by josephdecock** [comment]
> not the right license

This is distinct from no license at all? So non prod environments would be usable?

**Comment by brockallen** [comment]
Well, that's still open for discussion. If there's no license at all I'd say it should work, but I proposed we log that you're using an Enterprise level feature so you'd know you can't just then buy Starter, for example.

**Comment by leastprivilege** [comment]
agreed
