### ISSUE TITLE
Handling of licensed features going forward

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#1268]
to expand on https://github.com/DuendeSoftware/IdentityServer/issues/1266

Maybe we should do this:

* no license: always emit warning when a feature is used that requires an Edition > Starter
* license present: fail if feature is used that is not licensed

We probably need to make an exception for using multiple issuers because that often happens by accident - IOW warn only.

**Comment by brockallen** [comment]
For 6.3 or 7.0?

**Comment by brockallen** [comment]
Submitted a PR to do the logging piece. I anticipate feedback that we're now spamming the logs.
