### ISSUE TITLE
OidIReturnUrlParser nullability does not conform to IReturnUrlParser.ParseAsync

### ISSUE THREAD

**Issue by rabuckley** [DuendeSoftware/IdentityServer#1343]
**Which version of Duende IdentityServer are you using?**

Latest

**Describe the bug**

`OidIReturnUrlParser.ParseAsync` returns `null` when the `returnUrl` is not valid, but the interface (`IReturnUrlParser`) and its implementation state that the return value is non-nullable.

**Comment by josephdecock** [comment]
This is fixed in the new 6.3.4 release. Thanks again @rabuckley!
