### ISSUE TITLE
BackchannelAuthenticationRequestValidator inserts an unwanted string format item when calling LogError

### ISSUE THREAD

**Issue by Hoddikr** [DuendeSoftware/IdentityServer#1345]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

.NET 6

**Describe the bug**

__BackchannelAuthenticationRequestValidator__ calls __LogError__ with a string format item which results in an exception when __LogWithRequestDetails__ is called. 

A permalink directly to the line that causes the error:
https://github.com/DuendeSoftware/IdentityServer/blob/d933a168074d7248226241acd1b96d1910baf8bd/src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs#LL410C9-L410C9

**To Reproduce**

Implement __IBackchannelAuthenticationUserValidator__ and make a ciba request that results in any __Error__ value that is not one of the below:
* OidcConstants.BackchannelAuthenticationRequestErrors.AccessDenied
* OidcConstants.BackchannelAuthenticationRequestErrors.ExpiredLoginHintToken
* OidcConstants.BackchannelAuthenticationRequestErrors.UnknownUserId
* OidcConstants.BackchannelAuthenticationRequestErrors.MissingUserCode
* OidcConstants.BackchannelAuthenticationRequestErrors.InvalidUserCode
* OidcConstants.BackchannelAuthenticationRequestErrors.InvalidBindingMessage

**Actual behavior**

__LogError__ calls __LogWithRequestDetails__ with the string format item "{error}" within the message which will result in the following error being logged:
```
Error logging An error occurred while writing to logger(s). (Index (zero based) must be greater than or equal to zero and less than the size of the argument list.), request details: 
```

**Expected behavior**

LogError logs the error with the Error value from __BackchannelAuthenticationUserValidationResult.Error__ :
```
Unexpected error from IBackchannelAuthenticationUserValidator: <The error returned from the implementation of IBackchannelAuthenticationUserValidator.ValidateRequestAsync> 
```

**Additional context**

This arises when we have an implementation of __IBackchannelAuthenticationUserValidator__ where __ValidateRequestAsync__ populates the field __BackchannelAuthenticationUserValidationResult.Error__ with a value that is not one of the below:
* OidcConstants.BackchannelAuthenticationRequestErrors.AccessDenied
* OidcConstants.BackchannelAuthenticationRequestErrors.ExpiredLoginHintToken
* OidcConstants.BackchannelAuthenticationRequestErrors.UnknownUserId
* OidcConstants.BackchannelAuthenticationRequestErrors.MissingUserCode
* OidcConstants.BackchannelAuthenticationRequestErrors.InvalidUserCode
* OidcConstants.BackchannelAuthenticationRequestErrors.InvalidBindingMessage

This does not cause any actual errors or unexpected behavior in the ciba flow itself, but the error logs do not log the expected errors because of the additional string format item.

**Comment by Hoddikr** [comment]
@brockallen @josephdecock  Looks like this should do it, thanks.

**Comment by brockallen** [comment]
@Hoddikr Are you requesting that we patch this on 6.2.x, or are you ok waiting for 7.0?

**Comment by Hoddikr** [comment]
@brockallen 7.0 would be OK.
