### ISSUE TITLE
Consider EF ExecuteUpdate and SetProperty for our various cleanup processes

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1351]
Seems there's a feature in EF7 where we don't have to load all the records to then update them. This might make some of our update and cleanup workflows work better.

**Comment by josephdecock** [comment]
Docs for reference - https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete

**Comment by bbartels** [comment]
I created this PR to use ExecuteDelete during frequently used persistedgrant operations https://github.com/DuendeSoftware/IdentityServer/pull/1427

**Comment by josephdecock** [comment]
In addition, we would also like to consider fuzzing the startup time of the cleanup job to mitigate the "thundering herd" issue, where all scaled instances start their job at once.
