### ISSUE TITLE
Consider adding additional detail code to events

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1359]
Consider adding an additional code or sub-id to the events, so that events can be distinguished with better granularity by the id.

```
{
  "EventType": "Failure",
  "Id": 1011,
  "Message": "Unknown client",
  "SubId": 1 // <----- add this new id
  //... rest omitted
}
```
So that this event can be distinguished from this one, without comparing Message strings:

```
{
  "EventType": "Failure",
  "Id": 1011,
  "Message": "Invalid client secret",
  "SubId": 2 // <-----
 }
```

See https://github.com/DuendeSoftware/Support/issues/666

**Comment by brockallen** [comment]
@AndersAbel Do we have anything like this in our newer OTel work?

**Comment by AndersAbel** [comment]
@brockallen OTel works with tags, which are strings. I would say that we do not add anything new to the events. If there's something more needed, we should look into solving that through OTel. Please also note that OTel metrics are as far (as I understand) meant to drive dash-board overviews. The details for troubleshooting are in the traces and logs.

**Comment by brockallen** [comment]
To consider if needed, or maybe we have another way already w/ OTel.

**Comment by AndersAbel** [comment]
I think this is something that should be handled by the improved logging infrastructure in .NET 8 (which is compatible with oTel).
