### ISSUE TITLE
Consider changing the ServerSideSession Id from an `int` to a `long`

### ISSUE THREAD

**Issue by TLYoz** [DuendeSoftware/IdentityServer#1387]
The schema update introduced in V6.1 added ServerSideSessions table. It has `[Id] int NOT NULL IDENTITY`. I would expect the sessions to be a volatile and large table do we not see an issue with consuming the capacity of this Maxing out?

I may be misunderstanding how this new feature will operate. Is it expected that the number of Sessions will be similar to the number of Subjects. 

I am tempted to disable it due to this concern. So am looking for reassurance really.

**Comment by AndersAbel** [comment]
@TLYoz We have looked at this and this is indeed something we overlooked in the design. We are looking into possibilities to change the Id to a long, but we need to be careful with how it would affect existing deployments.

It is also worth noting that the `Id` is only present on the entity we ship as part of our EF package. Internally IdentityServer uses a `string` key. Someone implementing their own storage layer is not affected by the `int` limitation.

**Comment by TLYoz** [comment]
OK. We are using your EF package. But if it is a string internally why not use a guid or are you concerned about insert performance and re-indexing.

**Comment by TLYoz** [comment]
So the other question. As it states this is enabled by default in 6.1 what steps can we take to disable it so this overrun cant occur

**Comment by TLYoz** [comment]
Also. If we run the migration script using BIGINT does anyone for see any issues with us using your underlying EF module with an Int32 in the DTO (obviously I understand the overrun) but the code will be easier to change that upgrading the table later.

**Comment by josephdecock** [comment]
> So the other question. As it states this is enabled by default in 6.1 what steps can we take to disable it so this overrun cant occur 

Server side sessions are only enabled if you explicitly [enable them and add the services to DI](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/#enabling-server-side-sessions). Maybe there's something incorrect or misleading elsewhere in the docs - can you point me at what you're looking at in the docs please?

**Comment by 4865783a5d** [comment]
> OK. We are using your EF package. But if it is a string internally why not use a guid or are you concerned about insert performance and re-indexing.

Guid's generated by EF Core's ValueGenerator cause fragmentation issues in a webfarm/with parallel inserts as those Guid's are not sequential. 

https://github.com/dotnet/efcore/issues/30753

**Comment by brockallen** [comment]
If/when we do this, I think it requires lots of docs around the actual DB update for systems that have no down time. Think about what the default migrations look like and how that would compare to an actual large scale system and how appropriate/inappropriate it would be. Perhaps either advice that the DBA do something to help migrate, or an example of a custom store that handles the migration record by record?

**Comment by AndersAbel** [comment]
The impact of changing the data type depends on the database engine and volume of records. Most deployments should have some less busy hours where it is possible to run a simple alter column command and change the data type.

For deployments where that would cause unacceptable downtime, the solution is dependent on the DB engine used and should be handled by a custom database migration script. For example, SQL Server Enterprise Edition has an online index rebuild feature that should allow this change to be run without interrupting access to the table.

**Comment by brockallen** [comment]
> For deployments where that would cause unacceptable downtime, the solution is dependent on the DB engine used and should be handled by a custom database migration script. For example, SQL Server Enterprise Edition has an online index rebuild feature that should allow this change to be run without interrupting access to the table.

Did we open an issue then to document this?

**Comment by AndersAbel** [comment]
> > For deployments where that would cause unacceptable downtime, the solution is dependent on the DB engine used and should be handled by a custom database migration script. For example, SQL Server Enterprise Edition has an online index rebuild feature that should allow this change to be run without interrupting access to the table.
> 
> Did we open an issue then to document this?

I included it in https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/368
