### ISSUE TITLE
Redirecting back to client application after logging out from the external identity provider

### ISSUE THREAD

**Issue by okhara** [DuendeSoftware/IdentityServer#1404]
Identity server version 6.2.3
.NET version 6.0

**Redirecting back to client application after logging out from the external identity provider**

User is not redirected back to the client application from external identity provider, when identity server is configured for asp.net identity.
For example, if we use one of the [quickstart projects](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Quickstarts/5_AspNetIdentity) from duende samples and add oidc identity provider (we can use one of the clients from https://demo.duendesoftware.com/) we will be able to login through the identity provider successfully, but when we try to logout, process will go through logout to the identity provider and will not redirect back to the identity server and to the client application.

**To Reproduce**

1. Configure web application as client and identity server for asp.net identity (`.AddAspNetIdentity<ApplicationUser>()`).
2. Add oidc identity provider (`.AddInMemoryOidcProviders`).
3. Log into the client application through identity server using external identity provider configured in the second step.
4. Log out from the client application.

**Expected behavior**

User is logged out from client application, identity server and external identity provider, after which user is redirected back to client application.

**Actual behavior**

User is not redirected back to the client application.

**Solution**

[Link to PR](https://github.com/DuendeSoftware/IdentityServer/pull/1265)
After some debugging of the duende and Microsoft sources, I've discovered that the reason for the redirection problem is the absence of id token. SignOutScheme which is used to retrieve id token from the user is set to default value, but default authentication scheme after configuring identity server for asp.net identity is changed to Identity.Application.

**Comment by josephdecock** [comment]
This was resolved in #1265
