### ISSUE TITLE
Consider making ServerSideSessionStore.GetAndRemoveExpiredSessionsAsync virtual

### ISSUE THREAD

**Issue by AndersAbel** [DuendeSoftware/IdentityServer#1433]
Allows for customization using a derived class.

**Comment by brockallen** [comment]
Is this from a customer request (that may be blocked), or did this just come up from your own casual observations?

**Comment by AndersAbel** [comment]
It's a customer request.

**Comment by brockallen** [comment]
Yes, this got released in a patch, then merged into main on Nov 1, 2023.
