### ISSUE TITLE
Remove deprecated GetLogoutNotificationContext

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1436]
`GetLogoutNotificationContext` is marked as `[Obsolete("Unused and will be removed in a future version. Use the APIs on the IUserSession directly instead.")]`, with a comment `// TODO: remove in 7.0`.

**Comment by brockallen** [comment]
On a side note, for 7.0 it might be worthwhile combing thru the codebase for other messages like this left for our future selves.

**Comment by josephdecock** [comment]
This was closed in #1457
