### ISSUE TITLE
Add Otel metrics to PAR implementation

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1445]

**Comment by josephdecock** [comment]
@AndersAbel, after your work on OTEL metrics and my work on PAR both get merged, I think we want to add OTEL metrics to the PAR endpoint as well. Also, I didn't introduce new events for PAR, or emit any existing events from the PAR code. What are your thoughts on that? I did it this way since we're trying to emphasize OTEL and de-emphasize our events.

**Comment by AndersAbel** [comment]
I agree to not introducing new events. Sounds good adding otel metrics once both are merged.

**Comment by josephdecock** [comment]
We should instrument /connect/par and also we should update the instrumentation in /connect/authorize to tag requests that used par. We can use `ValidatedAuthorizeRequest.IsPushedAuthorizationRequest` to know in the authorize endpoint if the request was pushed.

**Comment by brockallen** [comment]
This is now merged: https://github.com/DuendeSoftware/IdentityServer/pull/1456
