### ISSUE TITLE
ApiScope - Created, Updated, LastAccessed, NonEditable

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/IdentityServer#15]
Hi.

I've noticed that ApiScope (model, entity, and database) does not follow the same pattern as ApiResource, IdentityResource, and Client, as it does not include the properties mentioned (Created, Updated, LastAccessed, NonEditable).

Do you plan addind them? Or removing them from the other models?
Or may be add some mechanism to extend the database model with this kind of things (we only use Created and Updated).

Thanks.

**Comment by brockallen** [comment]
Good catch. I think if we had noticed when adding those in the prior release we would have added them. Having said that, we really want to avoid breaking changes in the next release, and a schema change would cause that. 

We will discuss. Thanks.

**Comment by brockallen** [comment]
There are also some newer tables that don't allow renaming. I need to check up on those as well.

**Comment by brockallen** [comment]
Would it also make sense to add these to the new *IdentityProvider* table? // @scottbrady91

**Comment by scottbrady91** [comment]
Yeah, that would be useful.
