### ISSUE TITLE
OpenTelemetry Metrics Naming

### ISSUE THREAD

**Issue by Tornhoof** [DuendeSoftware/IdentityServer#1514]
I know it's probably too late for this, but maybe consider doing a breaking change for that in a next version, as some of the names are not well chosen (imho) or a way to disable individual ones.

Your new OpenTelemetry implementation emits certain metrics:
Two of those are named:
- failure
- success

Your detailed metrics names are fine I think, I'm only talking about the  high level ones in https://docs.duendesoftware.com/identityserver/v7/diagnostics/otel/metrics/

According to https://opentelemetry.io/docs/specs/semconv/general/metrics/
"Metric names and attributes exist within a single universe and a single hierarchy. Metric names and attributes MUST be considered within the universe of all existing metric names. When defining new metric names and attributes, consider the prior art of existing standard metrics and metrics from frameworks/libraries."

and "Semantic ambiguity SHOULD be avoided. Use prefixed metric names in cases where similar metrics have significantly different implementations across the breadth of all existing metrics. "

Let's take a look at other metric names:
aspnetcore_routing_match_attempts
dns_lookup_duration_bucket

The name failure and/or success are not well chosen, they are ambiguous and might as well collide with other similarily pre-existing names. The discoverability is not good.

This is how it looks like in grafana's explorer:
![grafik](https://github.com/DuendeSoftware/Support/assets/7989549/a5a2ebdc-9fa9-47e7-9465-a0847cd734d5)

I'm not even sure how to rename these properly, according to guidelines something like failure_count_identityserver would be correct or something similar.

Unfortunately, filtering metrics is apparently not trivial in .NET's OpenTelemetry Implementation,, most libraries which support that, do that with some kind of internal filter logic, but e..g. aspnetcore metrics apparently removed it in a recent version and only supports it for tracing

**Comment by Tornhoof** [comment]
> Is there any way to include the Meter name in the selection in Grafana?

Not that I can see, it's not even visible in the metadata attributes.

As for naming, the following are the httpclient names:
<img width="483" alt="Screenshot 2024-01-29 080937" src="https://github.com/DuendeSoftware/IdentityServer/assets/7989549/40c53462-236c-4d72-bd03-fd3048bd6d4b">

So I would rename the existing ones similarily:
- Prefix everything with identityserver_

I wouldn't do any postfixes like _count or _sum, they are probably not useful for the normal counters. httpclient apparently uses postfixes to differentiate between the three different meter types (bucket, sum, count).

As for failure and success, I'm not even certain I would include them at all, in your docs you write that some failures are expected, so I do not know what use that metric should be. I would personally just keep the detailed ones and remove those two fully.

**Comment by AndersAbel** [comment]
@Tornhoof Please see #1515 and comment on what you think.

**Comment by brockallen** [comment]
PR merged. We'll work on a patch release now.
