### ISSUE TITLE
CryptographicException while calling /.well-known/openid-configuration (.NET 8)

### ISSUE THREAD

**Issue by Tobias-08** [DuendeSoftware/IdentityServer#1534]
**Which version of Duende IdentityServer are you using?**

7.0.1

**Which version of .NET are you using?**

.NET 8

**Describe the bug**

Calling `/.well-known/openid-configuration` leads to `CryptographicException: The system cannot find the file specified` since we migrated from .NET 6/IdentityServer 6.x to .NET 8/IdentityServer 7.x.

**To Reproduce**

- Setup an IdentityServer project in .NET 8 and serve it via IIS with `Load user profile: false`.
- Call `/.well-known/openid-configuration`.

**Expected behavior**

It should work in .NET 8 even if `Load user profile` is set to `false`.

**Log output/exception with stacktrace**

```
CryptographicException: The system cannot find the file specified.
System.Security.Cryptography.X509Certificates.CertificatePal.FilterPFXStore(ReadOnlySpan<byte> rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan<byte> rawData, string fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan<byte> data)
System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(byte[] rawData)
Duende.IdentityServer.Services.KeyManagement.X509KeyContainer.ToSecurityKey() in X509KeyContainer.cs
Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore+<>c.<GetValidationKeysAsync>b__5_0(KeyContainer x) in AutomaticKeyManagerKeyStore.cs
System.Linq.Enumerable+SelectArrayIterator<TSource, TResult>.Fill(ReadOnlySpan<TSource> source, Span<TResult> destination, Func<TSource, TResult> func)
System.Linq.Enumerable+SelectArrayIterator<TSource, TResult>.ToArray()
Duende.IdentityServer.Services.KeyManagement.AutomaticKeyManagerKeyStore.GetValidationKeysAsync() in AutomaticKeyManagerKeyStore.cs
Duende.IdentityServer.Services.DefaultKeyMaterialService.GetValidationKeysAsync() in DefaultKeyMaterialService.cs
Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(string baseUrl, string issuerUri) in DiscoveryResponseGenerator.cs
Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in DiscoveryEndpoint.cs
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in MutualTlsEndpointMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in DynamicSchemeAuthenticationMiddleware.cs
Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in BaseUrlMiddleware.cs
Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Additional context**

Background:

- We are running IdentityServer in IIS with an application pool configured with `Load user profile: false`.
- This worked in .NET 6 but does not work in .NET 8.
- It works in .NET 8 if we set `Load user profile` to `true`.

Theory:

- The behaviour of `X509Certificate2`-constructor might have changed from .NET 6 to .NET 8 so that the [workaround](https://github.com/DuendeSoftware/IdentityServer/blob/aff8930ebdcbcb3e2a4c8713a3fdf88712c757de/src/IdentityServer/Services/Default/KeyManagement/X509KeyContainer.cs#L103) (type check) in IdentityServer's `X509KeyContainer`-implementation for the `Load user profile: false`-case might not work anymore.

**Comment by AndersAbel** [comment]
@brockallen @josephdecock The exception type was changed in .NET 7. So technically we should patch IdSrv 6.x. But end of life for .NET 7 is less than two months away. I think a fix for IdSrv 7.x is enough. What do you think?

**Comment by AndersAbel** [comment]
@Tobias-08 Do you think you could help me to get a value out of the exception thrown? I would need the value of `CryptographicException.HResult`. I assume that it should be `0x80070002` (=-2147024894), but I would like to verify before creating the patch.

**Comment by AndersAbel** [comment]
@Tobias-08 If we merge this and put out a preview on Nuget, would you be able to help us test it?

@brockallen Could we merge this and put out another preview on 7.0.2 to get it tested in a proper environment? It's obviously not testable on a local development setup because the user profile is always available then.

**Comment by Tobias-08** [comment]
@AndersAbel Yes, of course.

**Comment by brockallen** [comment]
We're working on putting out a 7.0.3-preview.1 to test.

**Comment by brockallen** [comment]
We've pushed a 7.0.3-preview.1 to NuGet with the proposed fix. Please have a look and let us know how it works. Thanks.

**Comment by Tobias-08** [comment]
@brockallen @AndersAbel `7.0.3-preview.1` works as expected in my setup, i. e. it works with .NET 8 and `Load user profile: false`.

Thanks!

**Comment by brockallen** [comment]
[7.0.3](https://github.com/DuendeSoftware/IdentityServer/milestone/53) Has been pushed to NuGet. Thanks!
