### ISSUE TITLE
License emulation for non-prod environments

### ISSUE THREAD

**Issue by AndersAbel** [DuendeSoftware/IdentityServer#1561]
When running without a license we always emit warnings if features that require higher level licenses are used. These warnings are not possible to disable and might be confusing. There is also always a risk that someone accidentally uses a features that requires a higher level license and that will be blocked once a license is added in production.

We should add a possibility for users to indicate already during dev/test what license tier they want to use. That would remove the warning logs for features they will have access, but also enforce the licensing rules for features they do not have access to.

This could be implemented by magic string licenses. If they use a license key of "business" that would allow business features (removing the warning for automatic key management) but also enforce that they cannot use dynamic providers etc that are enterprise features. The main logging message that they are running without a license should be kept.

**Comment by josephdecock** [comment]
Instead of magic strings, we'll control this with explicit configuration. The options shouldn't be combined with a real license, so need to decide if that is an exception, or just logged (and at what level of severity).
