### ISSUE TITLE
Delete retired keys even if they can't be unprotected

### ISSUE THREAD

**Issue by RolandGuijt** [DuendeSoftware/IdentityServer#1572]
With the DeleteRetiredKeys option enabled keys from any configured store are now not deleted if they can't be unprotected.
Please see the way the keys collection is built before [this](https://github.com/DuendeSoftware/IdentityServer/blob/e9860c6488f90e8fbc11a4452b9dd111dbfae933/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs#L463) line of code.

Consider proceeding with the delete without unprotecting the key first (using just the "Created" property on the keystore entry)

**Comment by brockallen** [comment]
I am unsure about this, since we don't know if there are other nodes that can unprotect them? Which view of the DB is correct? This is why it's always been left for someone else (like an admin or dev) to think about which ones need to be deleted, and they can do that manually.
