### ISSUE TITLE
EF: Handle OperationCanceledException instead of TaskCanceledException in UnhandledExceptionLoggingFilter

### ISSUE THREAD

**Issue by RolandGuijt** [DuendeSoftware/IdentityServer#1587]
OperationCanceledException could be the more appropriate exception to check for because some APIs just raise that.

See also: https://blog.stephencleary.com/2022/03/cancellation-3-detecting-cancellation.html#:~:text=And%20since%20TaskCanceledException%20derives%20from,Catch%20OperationCanceledException%20instead

And:
https://github.com/DuendeSoftware/Support/issues/1377

**Comment by josephdecock** [comment]
This looks like a straightforward change, and a good one. Just waiting on the licensing changes to finish tests, as automated tests that check logs were also done there.
