### ISSUE TITLE
`ClientConfigurationStore` should depend on `IConfigurationDbContext`

### ISSUE THREAD

**Issue by AndersAbel** [DuendeSoftware/IdentityServer#1616]
`ClientConfigurationStore` depends directly on `ConfigurationDbContext` which means it doesn't work for someone supplying a custom implementation type.

It should instead inject `IConfigurationDbContext`.

See [support/#1444](https://github.com/DuendeSoftware/Support/issues/1444)

**Comment by josephdecock** [comment]
Flagged as a breaking change to highlight in the release notes, but I think we can justify doing this in a minor release as impact of break is low, and this is bug.
