### ISSUE TITLE
Duplicate iat claim when upgrading from IS4

### ISSUE THREAD

**Issue by eduardsocea** [DuendeSoftware/IdentityServer#1628]
**Which version of Duende IdentityServer are you using?**
v7.0.6

**Which version of .NET are you using?**
v8.0.303

**Describe the bug**
When upgrading from IdentityServer4 (IS4) to IdentityServer7 (IS7), some existing tokens generated with IS4 may cause issues after refresh. Once a IS4 token is refreshed, the newly generated IS7 token may break the introspection response based on [RFC-7662 specification.](https://datatracker.ietf.org/doc/html/rfc7662#section-2.2)

As per RFC 7662, `iat` is optional and an Integer timestamp.
Right after the upgrade, for some tokens which are refreshed, the returned `iat` is an array of Integer type.

**To Reproduce**
1. Setup Identity Server 4.
2. Configure a Client with `offline_access` scope and `updateAccessTokenClaimsOnRefresh: false`. 
3. Perform authorization and generate a pair of access_token & refresh_token and keep the refresh_token
4. Upgrade the system to Identity Server 7
5. Using the refresh_token from step 3, generate a new pair of access_token & refresh token
6. Call /introspect endpoint with the refresh_token from step 5.
7. `iat` will be returned as an Array of Integer

Root cause:
- In Identity Server 4, `iat` claim is stored in the persisted grant.
- Since `updateAccessTokenClaimsOnRefresh` is set to false, the system will take the existing persisted grant and copy all the claims: [TokenResponseGenerator](https://github.com/DuendeSoftware/IdentityServer/blob/4c83776c01142277696555af455cfbcd7ca7322f/src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs#L190);  [TokenValidator](https://github.com/DuendeSoftware/IdentityServer/blob/4c83776c01142277696555af455cfbcd7ca7322f/src/IdentityServer/Validation/Default/TokenValidator.cs#L442)
- In Identity Server 7, the `iat` claim is added manually in the introspection endpoint. [TokenValidator](https://github.com/DuendeSoftware/IdentityServer/blob/4c83776c01142277696555af455cfbcd7ca7322f/src/IdentityServer/Validation/Default/TokenValidator.cs#L425)
- In the [IntrospectionResponseGenerator](https://github.com/DuendeSoftware/IdentityServer/blob/4c83776c01142277696555af455cfbcd7ca7322f/src/IdentityServer/ResponseHandling/Default/IntrospectionResponseGenerator.cs#L95), the extension method `ToClaimsDictionary` will create an array if duplicate claim exists, regardless of RFC 7662.

**Expected behavior**
1. [Upgrade documentation](https://docs.duendesoftware.com/identityserver/v7/upgrades/) should contain information about this breaking change.
2. The method `ToClaimsDictionary` creates a dynamic response based on the enumeration of the Claims. By not having any sanitizer, it is easy to break RFC 7662. I would expect to have a sanitizer in order to make sure that RFC 7662 is followed and proper Warnings / Errors to be logged. Otherwise, the error is failing silently and noticed by the consumer (Client).

**Additional context**
I found another github issue posted in 2021 which looks similar. From what I see, the other user experienced similar behavior (though there was an exception) and once all the broken refresh tokens were refreshed correctly, the user no longer experienced this issue.
https://github.com/DuendeSoftware/IdentityServer/issues/549

With the current behavior, the error is silent and is may cause users to be disconnected because the consumer cannot parse the response of introspection endpoint.

**Comment by josephdecock** [comment]
@eduardsocea thanks for raising this and for such a detailed bug report! This seems like a valid bug. 

It seems pretty clear to me that we should filter out "protocol" claims that we're already setting includg iat (but probably also iss, nbf, exp, and cnf) before we add the Claims from the reference token.


We're in the process of getting a release candidate of v7.1 ready. The intended timeline is that we'll publish a release candidate on Dec 12 and then officially release 7.1.0 on Jan 13. Do you need this fix before then? If so, we can backport the fix to the 7.0 branch.

**Comment by eduardsocea** [comment]
Thank you for the feedback. I do agree that all other claims should be filtered out as well.

The Dec 12 date for the RC sounds good. I already have in my project a temporary fix since the migration was critical. Probably I will remove my code once I upgrade to 7.1.0.
