### ISSUE TITLE
Open up DefaultCache for derived implementations

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#164]
If you don't mind...

Wouldn't it work if you made _cache and GetKey() protected in DefaultCache<>?
This way we could decorate that service and derive a custom implementation, adding remove only...

_Originally posted by @hugoqribeiro in https://github.com/DuendeSoftware/IdentityServer/discussions/145#discussioncomment-517404_

**Comment by damianh** [comment]
Consider dropping the interface in favour of `IDistributeCache` ( https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache?view=dotnet-plat-ext-5.0 )?

**Comment by brockallen** [comment]
I think our original decision to use that was to be abstracted away from the MSFT interface since it seems to have more semantics that we needed.
