### ISSUE TITLE
Investigate DPoP binding of refresh tokens

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1652]
The DPoP spec makes a distinction for refresh tokens between clients that are public and confidential - only public clients should use a DPoP proof, confidential clients already bind refresh tokens to the (authenticated) client. We need an automated test to prove that our behavior is correct.

See https://github.com/DuendeSoftware/Support/issues/1492

**Comment by dbfr3qs** [comment]
Just curious, what did you discover in the end @josephdecock ?

**Comment by josephdecock** [comment]
We have 3 items that we are going to address in future:

- Public clients need to be configured to require dpop to ensure that proofs are required when using refresh tokens. In future, we will make this automatic and not configurable.
- Confidential clients that are configured to require dpop require a proof during refresh. In future, we will make this not be required. We're still considering what to do if we get a proof token with a refresh request (probably ignore the proof)
- AccessTokenManagement currently always generates a proof if a proof key is available. In future, it will stop sending a proof when refreshing tokens for confidential clients.

**Comment by josephdecock** [comment]
To follow up here, some of my initial analysis turned out to be incorrect.

> Public clients need to be configured to require dpop to ensure that proofs are required when using refresh tokens. In future, we will make this automatic and not configurable.

This is not the case. We have checks that require a dpop proof if the RequireDPoP flag is on earlier in the pipeline which don't make a distinction between public and confidential clients, but later in the pipeline when we get to the validations for refresh token requests, we have more specific logic that ensures that if dpop was used to obtain a refresh token, it is also used with the refresh token. Confidential clients are afforded leeway to choose a new proof key, since the refresh token isn't bound to the original proof key, while public clients are required to use the same proof key throughout.

> Confidential clients that are configured to require dpop require a proof during refresh. In future, we will make this not be required. We're still considering what to do if we get a proof token with a refresh request (probably ignore the proof)

This overlooks the fact that even though a refresh token for a confidential client should not be bound to a proof key, a proof is still needed at the token endpoint to bind the _access token_ to a proof key. We already do ignore the proof in the sense that the refresh token is allowed to use a different proof key over time. And of course we use the proof to bind the access token to the proof key. The RequireDPoP option requires DPoP regardless of the grant type. Given these considerations, there is actually no need for us to make a change here.

> AccessTokenManagement currently always generates a proof if a proof key is available. In future, it will stop sending a proof when refreshing tokens for confidential clients.

This makes the same mistake as the previous bullet point. AccessTokenManagement wants a bound access token, so it will keep sending proofs.
