### ISSUE TITLE
AppAuth redirect URI validator should check post logout redirect URI collection for logout URI validation

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#176]
For consistency

**Comment by brockallen** [comment]
@leastprivilege I moved this to 6.1, since I didn't think you'd get to it for 6.0.

**Comment by leastprivilege** [comment]
It is this line of code - we can discuss

https://github.com/DuendeSoftware/IdentityServer/blob/c308d8303d35131e59d705ecd1eb4ec49d131691/src/IdentityServer/Validation/Default/StrictRedirectUriValidatorAppAuth.cs#L62
