### ISSUE TITLE
Add CancellationToken support for store interfaces

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#184]

**Comment by stefannikolei** [comment]
@leastprivilege I could have a look at this

**Comment by stefannikolei** [comment]
Should i add overloads (and use Default Interface Implementation - pointing to the method without cancellationToken) or just add the CancellationTokens to the current methods. But this will be invasive.. 

What direction do you want me to go?

**Comment by leastprivilege** [comment]
Thanks! Let's wait a little bit more until we start with the 6.0 work. Which will be soon.

**Comment by stefannikolei** [comment]
Ok if you want you can ping me then.

**Comment by leastprivilege** [comment]
Ah - you fixed it for Microsoft as well ;) nice!

https://github.com/dotnet/aspnetcore/pull/32736/files

**Comment by stefannikolei** [comment]
@leastprivilege adding the cancellationtoken support to all store interfaces leads to a big change. Should i go for it. Or is that time wasted?

**Comment by brockallen** [comment]
That work looks like it was recently started here: https://github.com/DuendeSoftware/IdentityServer/pull/328

**Comment by damianh** [comment]
Sorry I missed this issue. Hope I didn't step on toes @stefannikolei .
