### ISSUE TITLE
Default AlwaysIncludeClaimsInIdToken to true

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#20]
Since code flow is the new standard, id_token comes via back channel

pro
* eliminates one extra round trip to userinfo
* easier state management in profile service

cons
* larger id_token for id_token_hint situations

**Comment by brockallen** [comment]
Main concern is about client cookie size.

**Comment by brockallen** [comment]
Decided against given the subtle (and possibly client-breaking) behavior change.
