### ISSUE TITLE
IdentityProviders or OidcIdentityProviders

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/IdentityServer#245]
Hi.

I was trying to ensure that our database keeps up the 5.2 release...

In the upgrades documentation I see the new table is called `OidcIdentityProviders`, but in the source code this table is called `IdentityProviders`.

[Duende IdentityServer v5.1 to v5.2](https://docs.duendesoftware.com/identityserver/v5/upgrades/v5.1_to_v5.2/)
[ConfigurationDb.sql](https://github.com/DuendeSoftware/IdentityServer/blob/main/migrations/IdentityServerDb/Migrations/ConfigurationDb.sql)

Which one is correct?

**Comment by brockallen** [comment]
Ah, thanks. The docs were written and then there was a late breaking change. Fixed.
