### ISSUE TITLE
Consider changing DbContext ctors to support pooling

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#253]
Error: 'The DbContext of type 'ConfigurationDbContext' cannot be pooled because it does not have a single public constructor accepting a single parameter of type DbContextOptions.'

**Comment by stefannikolei** [comment]
I can have a look at it if you want.

**Comment by brockallen** [comment]
The issue is that we need our options in our db context. But if there's another way to achieve what we use them for, then sure -- have a look and let us know what you think we could do differently.

**Comment by stefannikolei** [comment]
Yeah saw it. I have a solution for that. Will make a pr

**Comment by brockallen** [comment]
FInally got your changes merged. I think I merged main into your branch thinking it would make the final merge back to main easier, but I guess I overwrote some of your work in doing so. My fault. So I made a new branch and cherry picked your commits. Sorry about that.
