### ISSUE TITLE
No templates found matching: 'isui'.

### ISSUE THREAD

**Issue by oscarlagatta** [DuendeSoftware/IdentityServer#255]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by leastprivilege** [comment]
This is not enough information. Please fill out the issue template, otherwise we cannot help you.
