### ISSUE TITLE
openid and profile scopes not working as expected

### ISSUE THREAD

**Issue by johnkwaters** [DuendeSoftware/IdentityServer#274]
Using either Postman with Grant Type ClientCredentials, or an Angular Client with Grant Type Code and PKCE, I can't seem to get an IdToken.
I have enabled openid and profile scopes and added those IdentityResources. I can see in the database that this is set up right.
But if I request the scope openid or profile it fails.

Angular oidc config:

{
  authority: 'https://hcdidentityserver.trailheadtechnology.com',
  client_id: 'directoryweb',
  redirect_uri: `${window.location.origin}/${TPage.SignInOIDC}`,
  response_type: 'code',
  scope: 'directory configuration activation IdentityServerApi',
  post_logout_redirect_uri: `${window.location.origin}/${TPage.SignOutOIDC}`
}

If I add openid and profile to the scopes above, I can't get a token

{"error":"invalid_scope"}

If I don't it works

Should the idToken automatically be returned with the accessToken - or what do I need to do to get one?

**Comment by brockallen** [comment]
> with Grant Type ClientCredentials

This flow will not emit an id_token because it's not OIDC and there's no user.

>  scope: 'directory configuration activation IdentityServerApi',

id_tokens are from OIDC and that requires the request to include the "openid" scope.

**Comment by brockallen** [comment]
>  But from the Angular SPA - should the caller request openid in the requested scopes? Should that result in an idToken being returned with the accessToken?

yes and yes :)

**Comment by leastprivilege** [comment]
Also the above snippet seems to indicate that you are doing the protocol interaction from JavaScript. This is not recommended for security sensitive applications. In that case you should consider

https://docs.duendesoftware.com/identityserver/v5/bff/

**Comment by johnkwaters** [comment]
Wow @brockallen ! Just when I thought I had taken our knowledge to a new level by using the oidc client in our SPA, with a Duende backend, the security worlds shifts again and now we have BFF with a whole new approach. Our new microservice acrchitecture actually uses Ocelot as an application gateway for our frontend - it seems putting the BFF in place in the Ocelot AspNetCore service might be a really good match? It's already handling proxying to various microservices. Thoughts on that approach? Any explicit BFF support for Ocelot?

**Comment by johnkwaters** [comment]
And @brockallen why are we not getting a refreshtoken back with the token response?

      new()
                {
                    ClientId = "directoryweb",
                    AllowedGrantTypes = GrantTypes.Code,
                    AllowOfflineAccess = true,
                    RequireClientSecret = false,
                    RedirectUris =           { "http://localhost:4200/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:4200/" },
                    FrontChannelLogoutUri =    "http://localhost:4200/signout-oidc",
                    RequirePkce = true,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "directory", "usage", "configuration", "activation",
                        IdentityServerConstants.LocalApi.ScopeName
                    }
                },

Is there some setting also needed in the oidc client in the SPA?

![image](https://user-images.githubusercontent.com/3422637/121682766-56203a80-ca71-11eb-9379-2c47f5b2c8cb.png)

**Comment by brockallen** [comment]
the "offline_access" needs to be in the requested scopes for a refresh token.

**Comment by johnkwaters** [comment]
And while we are at it.... when doing logout from the SPA, we see:

Refused to frame 'https://hcdidentityserver.trailheadtechnology.com/connect/authorize?client_id=directoryweb&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fsignin-oidc&response_type=code&scope=directory%20configuration%20activation%20IdentityServerApi%20openid%20profile&state=caf93e1d82f743d3b6596d67545870fb&code_challenge=7nGmpnPFywlvpcd1KbhyAavjYhA1Kojfei0yDJ6qaFc&code_challenge_method=S256&response_mode=query' because it violates the following Content Security Policy directive: "frame-src http://localhost:4200".

Any tips on that?

**Comment by brockallen** [comment]
Not sure exactly when/where that request is happening while you do logout from the SPA. But it sounds like there's an iframe somewhere making that request (you'll have to track that down), and it's causing the login page to show at IdentityServer. Given that the top document has a CSP policy that restricts any frames to localhost:4200, it won't be allowed to show. 

It sounds like something is amiss in your app workflow, and this likely should not be happening.

**Comment by NechiK** [comment]
It happens on IdentityServer `Account/Logout` page. It makes `connect/endsession/callback` API call, which returns HTML with iframe and src to FE route `signout-oidc`. On this page we call userManager.signoutRedirectCallback() method to finish logout.

As I understand IdentityServer tries to finish logout on the FE app without any redirects (i.e. clear storage) using iframe. The question is whose CSP could cause the error?

**Comment by brockallen** [comment]
> which returns HTML with iframe and src to FE route signout-oidc
>  On this page we call userManager.signoutRedirectCallback() method to finish logout.

Sounds like you have configured a front channel logout uri for a SPA using oidc-client. That's not the right architecture. I'd suggest looking at our SPA samples that use oidc-client -- you'll noticed they're not configured this way.

**Comment by brockallen** [comment]
Here's a link to a [SPA sample that uses oidc-client](https://github.com/DuendeSoftware/IdentityServer/tree/main/clients/src/JsOidc).

**Comment by johnkwaters** [comment]
I feel I am note quite grocking how this FrontChannelLogout works and why there is only ONE  such URL with multiple RedirectUrus and Post:LogoutRedirectUris

                new()
                {
                    ClientId = "directoryweb",
                    AllowedGrantTypes = GrantTypes.Code,
                    AllowOfflineAccess = true,
                    RequireClientSecret = false,
                    RedirectUris =           { "http://localhost:4200/signin-oidc", "https://hcdirectory.trailheadtechnology.com/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:4200/", "https://hcdirectory.trailheadtechnology.com/" },
                    FrontChannelLogoutUri =  "http://localhost:4200/signout-oidc", "https://hcdirectory.trailheadtechnology.com/signout-oidc" },
                    RequirePkce = true,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "directory", "usage", "configuration", "activation",
                        IdentityServerConstants.LocalApi.ScopeName
                    }
                },

As you see above I have different RedirectUris for localhost:4200 when developing and https://hcdirectory.trailheadtechnology.com when deployed. Should this instead be viewed as two different Clients?

**Comment by leastprivilege** [comment]
> why there is only ONE such URL

Well - because the spec says so. We know that this might be in the way for some scenarios and is inconsistent.

But you to ask yourself *why* you have multiple redirect URIs - the above code snippet looks like you want to use the same config for test and prod scenarios. This is nothing I would recommend - you should keep those environments separate and make sure you have strictly separate configurations for them.

**Comment by johnkwaters** [comment]
I had set up localhost:4200 and our deployed version of the same development branch to azure using the same clientid. We have different client ids for dev, test and prod, but was thinking of using the same dev client id for local and deployed develop branch. That doesn't work. So now I have a 4th client id to use for local development. Out of curiosity what is a scenario that would make sense where there are several redirect uris but only one front channel logout uri?

**Comment by leastprivilege** [comment]
You should have 1 client ID and 4 configurations...your prod config should not allow test clients. That's easily achievable with loading config on the fly and ASP.NET core's concept of hosting environments.

> Out of curiosity what is a scenario that would make sense where there are several redirect uris but only one front channel logout uri?

As I said, I think it is an oversight / shortcoming of the spec. But it is what it is ;)

**Comment by leastprivilege** [comment]
All set? Can we close this issue?

**Comment by johnkwaters** [comment]
Yes thanks!
