### ISSUE TITLE
Introspection fails occasionally due to duplicate cache key

### ISSUE THREAD

**Issue by ThomasN231** [DuendeSoftware/IdentityServer#283]
**Which version of Duende IdentityServer are you using?**
v5.2.0

**Which version of .NET are you using?**
.Net Core 3.1

**Describe the bug**

We have an API Scope (let's call it `A`), for which we also have an API Resource `A` and other API Resources `B` and `C`, which are also assigned to Scope `A`. Normally we would call the Api Scope exactly the same as the Api Resource (and additional ones if teams need additional scopes), but deviated in this particular instance due to the amount of client configurations we would have to adapt.

We recently got an issue report by a colleague who tried to call the Service using API Resource `A` using a reference token, for which the corresponding introspection request to our Identity Provider fails.
After a bit of digging around in the logs and the IdentityServer source code, we suspect that we run into a cache-related problem. We found in the failing request to the IdentityServer the message "More than one API resource with that name found. aborting", which pointed us to the `ApiSecretValidator` in the IdentityService. After looking into the cache, we found that the cache entry for the ApiResource `A` indeed had all 3 API Resources in them and after digging around more, we saw in the [`CachingResourceStore<T>`](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Stores/Caching/CachingResourceStore.cs) that for everything the exact same cache key is constructed. This is especially problematic for us in the case of `FindApiResourcesByNameAsync` and `FindApiResourcesByScopeNameAsync`, as they also have the same return type.

**To Reproduce**

- IdentityServer with EF Core and Identity integrations with caching enabled
- Have 2 (or more) Api Resources sharing the same scope
- Trigger a request to fill the cache with the Scope assignment (for instance using `client_credentials` flow)
- Trigger an introspection request for that API Resource that matches the scope name

**Expected behavior**

Introspection works for all API Resources.

**Comment by leastprivilege** [comment]
Thanks for reporting. We will look into it.

**Comment by ThomasN231** [comment]
Sure, did a change locally and would propose one later today.

**Comment by leastprivilege** [comment]
thanks!

**Comment by brockallen** [comment]
PR merged for the patch.
