### ISSUE TITLE
ProfileService not called

### ISSUE THREAD

**Issue by johnkwaters** [DuendeSoftware/IdentityServer#288]
I am adding the profile service:

`            var builder = services.AddIdentityServer(options =>
                {
                    options.EmitStaticAudienceClaim = true;
                    if (!string.IsNullOrEmpty(idso?.IssuerUri))
                    {
                        options.IssuerUri = idso.IssuerUri;
                    }

                    // set path where to store keys
                    options.KeyManagement.KeyPath = "/home/shared/keys";

                    // new key every 30 days
                    options.KeyManagement.RotationInterval = TimeSpan.FromDays(30);

                    // announce new key 2 days in advance in discovery
                    options.KeyManagement.PropagationTime = TimeSpan.FromDays(2);

                    // keep old key for 7 days in discovery for validation of tokens
                    options.KeyManagement.RetentionDuration = TimeSpan.FromDays(7);
                })
                **.AddProfileService<ProfileService>()**
                .AddMongoRepository()
                .AddClients()
                .AddIdentityApiResources()
                .AddPersistedGrants()
                .AddAspNetIdentity<MongoUser>();`

But my ProfileService isn't getting called;

![image](https://user-images.githubusercontent.com/3422637/122263596-798d2000-ce8b-11eb-93c2-dcaf40d60b09.png)

**Comment by leastprivilege** [comment]
`.AddAspNetIdentity` adds a profile service - so it overwrites. Register yours afterwards.

**Comment by johnkwaters** [comment]
Got it, thanks @leastprivilege . Will both run if I add my own afterwards? I see the default one works nicely to add roles - if I want to add additional things in mine, are they chained so I still get roles? I think I read something about the decorator pattern...

**Comment by johnkwaters** [comment]
I guess I can answer that myself after trying it - yes, it's chained!
