### ISSUE TITLE
acr_values idp does not bypass home realm discovery

### ISSUE THREAD

**Issue by Cephei** [DuendeSoftware/IdentityServer#295]
**Which version of Duende IdentityServer are you using?**
5.2.1

**Which version of .NET are you using?**
.net 5

**Describe the bug**
`acr_values=idp:value` does not seem to function.

**To Reproduce**
I'm just doing some early-stage testing:
`http://idsrvdomain.com/connect/authorize?client_id=cid&scope=openid&redirect_uri=http://fakeclient.com/callback&response_type=code&state=blah&acr_values=idp:ngt`

**Expected behavior**
I am expecting it to bypass the `/login` HRD interaction.

**Log output/exception with stacktrace**

```
[12:49:00 Verbose] Duende.IdentityServer.ResponseHandling.AuthorizeInteractionResponseGenerator
ProcessInteractionAsync

[12:49:00 Information] Duende.IdentityServer.ResponseHandling.AuthorizeInteractionResponseGenerator
Showing login: User is not authenticated

[12:49:00 Verbose] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
End authorize request. result type: Duende.IdentityServer.Endpoints.Results.LoginPageResult

[12:49:00 Verbose] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking result: Duende.IdentityServer.Endpoints.Results.LoginPageResult

Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.3/System.Net.WebSockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[12:49:00 Verbose] Duende.IdentityServer.Hosting.EndpointRouter
No endpoint entry found for request path: /login

```

Perhaps I'm misunderstanding something, but briefly looking at the source, I don't see any control flow that allows a supplied `idp` to trigger a redirect.

**Comment by leastprivilege** [comment]
You need to check the value on the login page and challenge the authentication handler - like our quickstart UI does.
