### ISSUE TITLE
DefaultTokenService not adding JwtClaimTypes.IssuedAt

### ISSUE THREAD

**Issue by ghstahl** [DuendeSoftware/IdentityServer#30]
**Which exact version are you using?**
5.0.0-preview.2

**Describe the bug**

[DefaultTokenService.cs](https://github.com/DuendeSoftware/IdentityServer/blob/6e68b1d6951586a2cac8435c6e8a58db9a734193/src/IdentityServer/Services/Default/DefaultTokenService.cs#L127)  

```
            // todo: cleanup
            // add iat claim
            //claims.Add(new Claim(JwtClaimTypes.IssuedAt, Clock.UtcNow.ToUnixTimeSeconds().ToString(), ClaimValueTypes.Integer64));

```
Is there plans to uncomment this code and get  JwtClaimTypes.IssuedAt back  as a claim?

**Comment by leastprivilege** [comment]
Are you missing the iat claim in your tokens?

It is here and should be hit whenever a JWT gets generated
https://github.com/DuendeSoftware/IdentityServer/blob/c308d8303d35131e59d705ecd1eb4ec49d131691/src/IdentityServer/Extensions/TokenExtensions.cs#L48

**Comment by leastprivilege** [comment]
It was indeed missing in reference tokens - that was a regression. Thanks!

Could you test if it works for you now?

**Comment by ghstahl** [comment]
reference_tokens is where I noticed it wasn't there.  However I did find the following was;

**Comment by leastprivilege** [comment]
it's fixed now. thanks!
