### ISSUE TITLE
Integrate with ASP.NET Endpoint Routing

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#32]

**Comment by SergeiIsayeu** [comment]
@brockallen is this still on the list/planned feature? Would love to have Open API/Swagger specs for all IDS endpoints

**Comment by brockallen** [comment]
We still need to [re-]investigate to determine the benefit.

**Comment by brockallen** [comment]
We decided we will always need our own middleware, so this doesn't seem beneficial.

**Comment by brockallen** [comment]
Reopening to re-evaluate in case something has changed and it's now worthwhile.

**Comment by brockallen** [comment]
Related: https://github.com/DuendeSoftware/IdentityServer/issues/1589
