### ISSUE TITLE
QUESTION: Should method accepting an Url as parameter support `System.Uri` overloads?

### ISSUE THREAD

**Issue by msschl** [DuendeSoftware/IdentityServer#342]
**Which version of .NET are you using?**

```shell
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\
```

**Question:**

Dotnet includes some analysers like [CA2234](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2234) which warn about URI, URL properties being of type string and not `System.Uri`.
> `A call is made to a method that has a string parameter whose name contains "uri", "Uri", "urn", "Urn", "url", or "Url" and the declaring type of the method contains a corresponding method overload that has a System.Uri parameter.`

The question therefore arises whether methods like the two below should also have an overload taking an `System.Uri` as parameter
```diff
namespace Duende.IdentityServer.Services
{
    public interface IIdentityServerInteractionService
    {
         Task<AuthorizationRequest> GetAuthorizationContextAsync(string returnUrl);
+         Task<AuthorizationRequest> GetAuthorizationContextAsync(Uri returnUrl);

         bool IsValidReturnUrl(string returnUrl);
+         bool IsValidReturnUrl(Uri returnUrl);
    }
}
```

**Comment by leastprivilege** [comment]
We do not have plans to add such overloads. Do you see any real benefit in this besides getting rid of that "analyzer suggestion" ?

**Comment by msschl** [comment]
I'm currently discussing the same question in the [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) repo (see [#9452](https://github.com/dotnet/aspnetcore/issues/9452)). ASP.NET Core however, is not planning on adding `System.Uri` overloads.

I don't understand why Microsoft is suggesting to use `System.Uri` instead of `String` and yet they themself use `String` in ASP.Net Core. Does using `System.Uri` come with a performance penalty compared to using bear strings? So is the current recommendation by Microsoft to disable this analyzer?

I'll reach out here again as soon as I have some more information from the ASP.Net Core team.

For identity server I don't know whether using `System.Uri` would simplify for example the `IReturnUrlParser` implementations or maybe even cause some free pref improvements.

**Comment by damianh** [comment]
https://refactoring.guru/smells/primitive-obsession

As some who is DDD orientated, I would prefer using a type over a string. Puts the onus on the call site to correctly construct the paramater. 

As usual, the tradeoff is against a breaking change/overload or `[Obsolete]` maintenance.

**Comment by msschl** [comment]
There is an ongoing discussion in [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/issues/5332) to further enrich an analyzers context with for example the project type or SDK to further reduce false positives.

To the `System.Uri` overloads mentioned in this issue: for ASP.Net Core the team is not planning on adding any `System.Uri` overloads. Hence, the analyzer - in my point of view - is falsely firing. Enriching the analyzers with additional context could help to reduce those false positives.

I am fine with closing this issue for now and would suggest waiting on what happens with those analyzers incorrectly fireing.

**Comment by brockallen** [comment]
We discussed, and I think we decided against this (mainly due to the pain in using the Uri class and the massive amount of change this would introduce). Thanks for the suggestion, though.
