### ISSUE TITLE
IIdentityServerBuilder.AddCookieAuthentication() refactor

### ISSUE THREAD

**Issue by Cephei** [DuendeSoftware/IdentityServer#344]
I've had a need to refactor around the default implementations of `AddRequiredPlatformServices` and `AddCookieAuthentication` when building with `AddIdentityServerBuilder()`.

`AddCookieAuthentication:`
I'm not using the default IdSrv cookie names and don't want their default registrations in the auth pipeline. However, I do want to leverage your internal `IdentityServerAuthenticationService` and `FederatedSignOutAuthenticationHandlerProvider` - which are registered internally as decorators. Both of which I cannot reuse to register without copy/pasting code.

Consider breaking-out the internal decorated registrations into a separate method. From what I can see, they are agnostic to authentication scheme and not dependent upon default cookies.

https://github.com/DuendeSoftware/IdentityServer/blob/a5b20b3b2978cc791f1a6bfce09c7eb248c54b29/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L71

`AddRequiredPlatformServices:`
This one is much easier for me to get around since everything is public and I can just create my own "RequiredPlatformServices" implementation. I had a need to make `IdentityServerOptions` be either scoped to the request or transient, instead of singleton. Primarily just so the `UserInteractionOptions` can be extensible for different front-end hosts that share the same idsrv backend. This issue is directly related to another issue I read about creating a more robust multi-tenant solution. Since there are such few singletons being registered in IdSrv that depend upon `IdentityServerOptions`, I was able to get around this fairly easily without creating lifetime conflicts.

**Comment by brockallen** [comment]
> I'm not using the default IdSrv cookie names and don't want their default registrations in the auth pipeline. However, I do want to leverage your internal IdentityServerAuthenticationService and FederatedSignOutAuthenticationHandlerProvider - which are registered internally as decorators. Both of which I cannot reuse to register without copy/pasting code.

If we provided a public extension method off of the *AuthenticationBuilder* that registered these two, would that help?

**Comment by Cephei** [comment]
For now, I've decided just to keep the default `AddCookieAuthentication()` in place as it's not creating much harm in registering the default `idsrv` scheme and leaving it unused, but I think your proposal would help us just keep the solution as lean or pure as possible.

The `AddRequiredPlatformServices()` as well as `AddDynamicProvidersCore()` requires us to make a bit more change to the default behavior - but that's specific to our needs in having a multi-tenanted Identity Server (sharing the IdSrv infrastructure but with multiple front-ends / issuers. Currently we have two, for our different product suites on different domains (`e.g. accounts.abc.com, accounts.xyz.com`) both pointing the this shared solution, but as we acquire more companies, we needed to build a solution to adapt with us.

I'm currently doing the following:
```c#
services.AddIdentityServerBuilder()
    .AddModifiedRequiredPlatformServices() // NOTE THAT THIS IS MODIFIED FROM IDSRV DEFAULTS
    .AddCookieAuthentication()
    .(...) // other default IdSrv extensions
    .AddModifiedDynamicProvidersCore() // NOTE THAT THIS IS MODIFIED FROM IDSRV DEFAULTS
```

```c#
/// <summary>
/// We are modifying the default AddDynamicProvidersCore() by removing their default
/// singleton registration of <see cref="DynamicProviderOptions"/>. This is because we've made 
/// <see cref="IdentityServerOptions"/> a Scoped registration in <see cref="AddModifiedRequiredPlatformServices"/>.
/// </summary>
private static IIdentityServerBuilder AddModifiedDynamicProvidersCore(this IIdentityServerBuilder builder)
{
    builder.AddDynamicProvidersCore();
    builder.Services.RemoveAll<DynamicProviderOptions>();
    builder.Services.AddScoped<DynamicProviderOptions>(svcs => svcs.GetRequiredService<IOptions<IdentityServerOptions>>().Value.DynamicProviders);

    return builder;
}
```

```c#
/// <summary>
/// We are modifying the default AddRequiredPlatformServices() by removing their default singleton
/// registrations of <see cref="IdentityServerOptions"/> and <see cref="PersistentGrantOptions"/>.
/// 
/// <see cref="IdentityServerOptions"/> are also configured to resolve dynamically based on hostname
/// to provide extensibility for <see cref="UserInteractionOptions"/>. This allows different front-ends
/// to have their own UI endpoints.
/// </summary>
private static IIdentityServerBuilder AddModifiedRequiredPlatformServices(this IIdentityServerBuilder builder)
{
    builder.AddRequiredPlatformServices();
    builder.Services.RemoveAll<IdentityServerOptions>();
    builder.Services.RemoveAll<PersistentGrantOptions>();
    builder.Services.AddScoped<PersistentGrantOptions>(resolver => resolver.GetRequiredService<IOptions<IdentityServerOptions>>().Value.PersistentGrants);
    builder.Services.AddScoped<IdentityServerOptions>(ctx =>
    {
        var iso = ctx.GetRequiredService<IOptions<IdentityServerOptions>>().Value;
        var hca = ctx.GetRequiredService<IHttpContextAccessor>();
        if (hca.HttpContext == null)
            return iso;

        var cache = ctx.GetRequiredService<IMemoryCache>();
        return cache.GetOrCreate<IdentityServerOptions>(
            $"{hca.HttpContext.Request.Host.Host}.iso",
            entry => CreateForTenant());

        IdentityServerOptions CreateForTenant()
        {
            // Currently, UnifiedUserInteractionOptions are optional, however,
            // we should probably enforce all tenants (Issuers) to register their own.
            var tenantUIOptions = ctx.GetService<UnifiedUserInteractionOptions>(); // tenants can register their own UI endpoints
            if (tenantUIOptions == null)
                return iso;

            var mapper = ctx.GetRequiredService<IMapper>();
            var clone = mapper.Map<IdentityServerOptions>(iso);
            clone.UserInteraction = mapper.Map<UserInteractionOptions>(tenantUIOptions); // extensible UI
            return clone;
        }
    });

    return builder;
}
```

**Comment by brockallen** [comment]
If we have time, we'll look at this for 6.0.

**Comment by brockallen** [comment]
PR was submitted to address the first part of your feature request: https://github.com/DuendeSoftware/IdentityServer/pull/423. Please review when you can.

**Comment by brockallen** [comment]
I finally just dug into your other ask in this issue. I don't think you need all of the modified DI APIs. Why can't you just add your custom options to DI after the standard AddIdentityServer? That would overwrite ours, no?

**Comment by brockallen** [comment]
Also, would this PR help in this regard?

https://github.com/DuendeSoftware/IdentityServer/pull/425
