### ISSUE TITLE
License issues?

### ISSUE THREAD

**Issue by magnusjjj** [DuendeSoftware/IdentityServer#371]
You say that 

"If you wish to evaluate or use the Duende™ software libraries in a NonCommercial Manner*
, you may download and access the source and/or binaries
at no charge under the Reciprocal Public License 1.5 (RPL-1.5) (the “RPL”);"

Can then the people using the libraries noncommerically share the code with other people under that license, even if those people have an unknown usage case?

The RPL has a specific section about not creating new licenses based on it that will make people confuse them with it. I can honestly say that I am confused about what I am allowed to do with it, given that I can't control the use people will have of my software.

**Comment by brockallen** [comment]
If your software is free open source, then you can reference the Duende IdentityServer NuGet packages from it. If someone else then takes your code and they use it (along with the referenced Duende IdentityServer NuGet packages) in a commercial context, then they are subject to the commercial license.

**Comment by brockallen** [comment]
Also, in this repo we're keeping the issue tracker for bug and feature tracking, and are using the [discussion boards](https://github.com/DuendeSoftware/IdentityServer/discussions) for general Q&A so if there's more conversation to be had, let us continue there please. Thanks!
