### ISSUE TITLE
Change Log Level

### ISSUE THREAD

**Issue by ishchatul** [DuendeSoftware/IdentityServer#385]
In the scenario that there are multiple keys and only one can unprotect we not expecting to see an error, maximum a Warning.
https://github.com/DuendeSoftware/IdentityServer/blob/5064cf2383cab47e1c3f180cf5b70a1c00b61710/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs#L435

In the case that no keys are found maybe then there should be an error and not just log Information

**Comment by brockallen** [comment]
It means you have bad data in the keys table. So that's why it felt like an error is better. Thoughts?

**Comment by ishchatul** [comment]
So if we get that error, it means the clean up is not working?

**Comment by brockallen** [comment]
> So if we get that error, it means the clean up is not working?

It means that the key in that table was protected with a data protection key that is no longer available.

**Comment by brockallen** [comment]
Any further input on this issue, @ishchatul?

**Comment by ishchatul** [comment]
All good
