### ISSUE TITLE
Configure BFF and IdentityServer with SPA on develop

### ISSUE THREAD

**Issue by PolyakovPavel** [DuendeSoftware/IdentityServer#428]
Hi.
How to properly configure BFF and IdentityServer when develop with the following architecture:
1. FrontEnd is VueJs SPA. Running develop on localhost:8080
2. Asp Net Core BFF with BFF Security Framework running on localhost:4004
3. IdentityServer running on localhost:4001

When the SPA (localhost:8080) receives a 401 response code from BFF, it is send request to localhost:4004/bff/login, then the user is redirected to localhost: 4001 (IdentitServer). When User is Authenticated, his redirected back to localhost:4004/signin-oidc.

Tell me how I should set up the project so that the return from IdentityServer occurs on localhost: 8080 (SPA).

My setting now: 
1.BFF
```c#
services.AddBff();
JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

services.AddAuthentication(options =>
{
    options.DefaultScheme = "Cookies";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
})
.AddCookie("Cookies")
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = "https://localhost:4001";

    options.ClientId = "bff";
    options.ClientSecret = "secret";
    options.ResponseType = "code";

    options.Scope.Add("api1");

    options.SaveTokens = true;
    options.GetClaimsFromUserInfoEndpoint = true;
});
```
2. IdentityServerClient
``` c#
// JavaScript BFF client
new Client
{
    ClientId = "bff",
    ClientSecrets = { new Secret("secret".Sha256()) },

    AllowedGrantTypes = GrantTypes.Code,

    // where to redirect to after login
    RedirectUris = { "https://localhost:4004/signin-oidc" },

    // where to redirect to after logout
    PostLogoutRedirectUris = { "https://localhost:4004/signout-callback-oidc" },

    AllowedScopes = new List<string>
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        "api1"
    }
}
```

P.S. When run SPA in same address with BFF (localhost:4004) everything works fine

**Comment by leastprivilege** [comment]
Are you using the .NET 6 SPA templates?

**Comment by PolyakovPavel** [comment]
I am using .NET 5. Sample code taked from ://docs.duendesoftware.com/identityserver/v5/quickstarts/js_clients/js_with_backend/
work fine, but only when Frontend and BFF on same project and host.

**Comment by damikun** [comment]
This is what I do with react frontend and is working... I'm my case frontend SPA is on port 5015..

Identity server:
```
                    ClientId = "spa",
                    ClientSecrets = { new Secret("secret".Sha256()) },
                    
                    AllowedGrantTypes = GrantTypes.CodeAndClientCredentials,

                    RedirectUris = { "https://localhost:5015/signin-oidc" },
                    
                    BackChannelLogoutUri = "https://localhost:5015/bff/backchannel",
                    
                    PostLogoutRedirectUris = { "https://localhost:5015/signout-callback-oidc" },

                    AllowedCorsOrigins = new List<string>
                    {
                        "https://localhost:5015", "http://localhost:5001",
                    },

                    AllowOfflineAccess = true,
                    AllowedScopes = { "openid", "profile", "api" }
```

BFF:
```
         .AddCookie("cookie", options =>
            {
                // set session lifetime
                options.ExpireTimeSpan = TimeSpan.FromHours(8);
                
                // sliding or absolute
                options.SlidingExpiration = false;
                
                // host prefixed cookie name
                options.Cookie.Name = "__SPA_FF";
                
                // strict SameSite handling
                options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Strict;
            })
            .AddOpenIdConnect("oidc", options =>
            {
                options.Authority = "https://localhost:5001";
                
                // confidential client using code flow + PKCE
                options.ClientId = "spa";
                options.ClientSecret = "secret";
                options.ResponseType = "code";
                options.ResponseMode = "query";

                options.MapInboundClaims = true;
                options.GetClaimsFromUserInfoEndpoint = true;
                options.SaveTokens = true;

                // request scopes + refresh tokens
                options.Scope.Clear();
                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.Scope.Add("api");
                options.Scope.Add("offline_access");
            });
```

and in react frontend i have just stupid react component for login protected by Private/Public router:

export default function Login() {

      useEffect(() => {
        window.location.href = LOGIN_ENDPOINT;
      }, [])

      return <></>
  }

**Comment by PolyakovPavel** [comment]
Thanks for your help. 
I tried it, but without success. 
When redirecting to IdentityServer, 
I get an error: "Sorry, there was an error: invalid_request. Invalid redirect_uri ".
Here is the request log that comes to IdentityServer:
```json
{
    "ClientId": "bff",
    "ClientName": null,
    "RedirectUri": null,
    "AllowedRedirectUris": [
        "https://localhost:8080/signin-oidc"
    ],
    "SubjectId": "anonymous",
    "ResponseType": null,
    "ResponseMode": null,
    "GrantType": null,
    "RequestedScopes": "",
    "State": null,
    "UiLocales": null,
    "Nonce": null,
    "AuthenticationContextReferenceClasses": null,
    "DisplayMode": null,
    "PromptMode": "",
    "MaxAge": null,
    "LoginHint": null,
    "SessionId": null,
    "Raw": {
        "client_id": "bff",
        "redirect_uri": "https://localhost:4004/signin-oidc",
        "response_type": "code",
        "scope": "openid profile api1",
        "code_challenge": "689hMn9gdq9Yc74hf_VCLfFbLk6Hf8rxfW-6rIUHbJQ",
        "code_challenge_method": "S256",
        "response_mode": "form_post",
        "nonce": "637683215202379469.OTMzY2E4YmQtODJjOS00ODczLWIyZWYtYmIyYzA1Yzg2MzQ1MGVjZTZmNWUtOWJiNS00N2YyLTg4YzItMzE4NmFmZDRjMjc1",
        "state": "CfDJ8FzKfyDelx9Ji_qJ9QWJSD3k30fY77Di2qrl04zYnyai8iKJLVe33ZwVd23r4gRXyhqhW9UZaNK4HFBH4qF4Sar_B4DnoX0pLsih-3lgw7tzikT0yGpvENZF7y4_kzDXkldixHzRDvQC5cR3DFUhNPvpeky4Wk22SIfXtgKzLJ_0N2LZIkvRNVr5_epCbBr2kOIfQzwwuuqjkxkRnBJZhw8pJbnL-4H9qxOEclaCT3pUqHPHlr-t7aOJ2pr17NXrc9oaUf_OY-HHVGrhpFvShqwYUmbZ6Pjq0gcFpf5kjE6mdGHfABRtNj2-qAt4SRbY8TAT1HADE90ZybtldVj54DVmvuTgDtW100a5h3qQh9_E25RgJE4H1Psla71PlxzweQ",
        "x-client-SKU": "ID_NETSTANDARD2_0",
        "x-client-ver": "6.7.1.0"
    },
    "$type": "AuthorizeRequestValidationLog"
}
```
P.S. After getting 401 error from BFF, use "window.location.replace(process.env.VUE_APP_REDIRECT)", where VUE_APP_REDIRECT is "https://localhost:4004/bff/login"  (BFF)

**Comment by brockallen** [comment]
Closing this since we don't have enough direction or info to repro or take any action.

**Comment by gundogduhasan** [comment]
Hi, 
I have the similar issue. I am using angular for SPA. Here is my configs;
BFF backend runs on http://localhost:50771

` services.Configure<AuthConfig>((Configuration.GetSection("IdentityServerSettings")));

            var authConfig = Configuration.GetSection("IdentityServerSettings").Get<AuthConfig>();

            services.AddAuthorization();
            services.AddBff();
            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "cookie";
                options.DefaultChallengeScheme = "oidc";
                options.DefaultSignOutScheme = "oidc";
            })
             .AddCookie("cookie", options =>
             {
                 // set session lifetime
                 options.ExpireTimeSpan = TimeSpan.FromHours(8);

                 // sliding or absolute
                 options.SlidingExpiration = false;

                 // host prefixed cookie name
                 options.Cookie.Name = "__Host-spa";

                 // strict SameSite handling
                 options.Cookie.SameSite = SameSiteMode.Strict;
             })
             .AddOpenIdConnect("oidc", options =>
             {
                 options.RequireHttpsMetadata = false;
                 options.Authority = authConfig.AuthorityUrl;
                 options.ClientId = "<spa-client-id>";
                 options.ClientSecret = "<spa-client-secret>";
                 options.ResponseType = "code";
                 
                 // query response type is compatible with strict SameSite mode
                 options.ResponseMode = "query";

                 // get claims without mappings
                 options.MapInboundClaims = false;

                 options.Scope.Add("role");
                 options.Scope.Add("openid");
                 options.Scope.Add("profile");
                 options.Scope.Add("<bff-api>");
                 options.Scope.Add("offline_access");
                 options.SaveTokens = true;
                 options.GetClaimsFromUserInfoEndpoint = true;
             });`
Configure part
`
 app.UseRouting();

            //app.UseCors("AllCors");
            app.UseAuthentication();

            app.UseBff();

            app.UseAuthorization();

            app.UseMiddleware<ExceptionLogMiddleware>();

            app.UseEndpoints(endpoints =>
            {
                var defaultBatchHandler = new DefaultODataBatchHandler();
                defaultBatchHandler.MessageQuotas.MaxOperationsPerChangeset = 10;

                endpoints.Expand().Select().Filter().OrderBy().Count().MaxTop(null);
                endpoints.MapODataRoute(
                    routeName: "<odata-route>",
                    routePrefix: "<odata-route>",
                    model: GetEdmModel(),
                    batchHandler: defaultBatchHandler
                    ).MapBffManagementEndpoints();
            });
`
BFF's spa project runs on localhost:4400,BFF's backend project runs on localhost:50771, identityserver works on localhost:5200
When i start request to 'bff/user' end point before login it's returns '401' as should be. But when i start request to 'bff/login' end point i am getting this error on debug 
'CORS request made for path: /connect/authorize from origin: http://localhost:4400 but was ignored because path was not for an allowed IdentityServer CORS endpoint'

The request address is
 '
http://localhost:5200/connect/authorize?client_id='spa-client-id'&redirect_uri=http%3A%2F%2Flocalhost%3A50771%2Fsignin-oidc&response_type=code&scope=openid%20profile%20role%20'bff-api'%20offline_access&code_challenge=nqs20wRFlZ2eX7MPb1_t34_H8R02oon1VJvLrGR1kjI&code_challenge_method=S256&nonce=638034982051904330.NGMwMTUzNTUtNDQ0YS00MGQwLTkwYzUtZGJmNDAxM2Q3ZTVhNWQwZTExODUtYzFlYi00N2YyLTg4MTktNmRiMDBjZjRkYTA1&state=CfDJ8GjV4rteP2NCot0f0GPOVye47BXEDQodgxffDNy8XlDUynAyesJ-Tk1NTQeGgQRanpbJIm9GLH4z-FGwrXfjmic0BAWbGGOW43uLv_npat1bOqvM7ETxfGdFBT5zvN7WZIB0WDldXJy8LPImCZNvIfjZj0PGvpdrqPLbRrs8hAhKwCtHTAsggmD2U8eUl7zsmkIexo4WUcgU8vMisUdwNE6yCTPUhAeDw8xiuqrvl6u_rlHerqiRCe_qH2JEQ7A2ygjWNZsJMngZ0VZrQYh4uLoKbHvbsqI4AfPu_GVf6vJzultmP1IRSVaP8mVopGxwVvzJP9q50rYLxPpKLG0FH15I8JqZqye1Ju3WDDNnqDF8gSwe1f_kmKuNhf-ak1RBKA&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0
'
as you can see redirect uri in the request address is 'localhost:50771/signin-oidc' this address is BFF's api address. But my spa client redirect uri is 'localhost:4400/signin-oidc'.

My question is my SPA client address and BFF's backend address most be same address(as port, as domain)? I am already using identity server 4 with implict flow but since implict flow does not secure any more i have to upgrade to bff. But my backend project and spa runs on different sub domains  on production, and different ports on development. Soo long story short are my addresses(spa and backend) can be different while using BFF? If it's can be done, what am i missing? Many thanks for your help.

Best regards.
