### ISSUE TITLE
Add built-in server-side sessions

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#430]

**Comment by adamwylde** [comment]
This is an important feature for us blocking our adoption of Identity Server as we need to be able to invalidate user sessions server side.

Thanks

**Comment by leastprivilege** [comment]
Thanks for the feedback!

> we need to be able to invalidate user sessions server side

As already mentioned - this can be accomplished today since this is really an ASP.NET Core feature.

That being said - I just bumped the milestone to 6.1 - so we are planning to work on that after the v6 release in January.

You can either wait for it, or use the Microsoft APIs directly in the meantime.

**Comment by maulik-modi** [comment]
@leastprivilege/@brockallen , would you please add some more description to help deciding whether to wait for 6.1 or do an upgrade to 6.0?

**Comment by brockallen** [comment]
We've not yet done our 6.1 feature planning, but I don't expect it to be released for at least 3 months. I don't know if that helps.

**Comment by brockallen** [comment]
We would like to have in here:
* configurable claim for a display name (for dashboards)
* service in DI that a allows for custom logic at login and logout time (e.g. perhaps to capture more data at login, and do some cleanup at logout)

**Comment by brockallen** [comment]
interface API for admins:
* query all sessions (returns data, plus ticket, plus client id list)
* revoke sessions (cookie, backchannel logout for all clients, and RT/ref tokens/codes revocation for clients list specified) w/ RevocationContext param

**Comment by brockallen** [comment]
Might need to support back channel SLO in IS itself, thus the SID in the store isn't the right one (upstream IdP SID vs IS SID). We might need another column in there to track those separately.
