### ISSUE TITLE
Consider supporting the OIDC prompt=create param

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#432]
https://openid.net/specs/openid-connect-prompt-create-1_0.html

I think we currently restrict the allowed set of prompt params to be the ones from the core spec. This would be a small modification to expand the allowed list internally. I don't think we'd do anything on the UI side, unless we wanted to introduce a new UI endpoint for registration (much like we might for "select account")?

**Comment by g7ed6e** [comment]
would you accept a PR with the below modifications ?
- add `prompt_values_supported` to the discovery endpoint
- add UI endpoint
- add redirection to the new UI endpoint when `prompt=create` is supplied to the authorize endpoint

**Comment by brockallen** [comment]
Not at this time, but thank you.

**Comment by g7ed6e** [comment]
Now that IS6 is released would you reconsider ? I’m migrating from IS4v4 to IS5/6 and would be happy to drop a custom IAuthorizeInteractionResponseGenerator.

**Comment by brockallen** [comment]
Yes, we will consider this request in our next round of planning. Thx.

**Comment by g7ed6e** [comment]
Great i will submit a PR. Thanks

**Comment by brockallen** [comment]
> Great i will submit a PR. Thanks

What I meant is that we'll consider it internally in our product planning. Please don't spend any time until we have confirmed that we want to add it - I don't want you to waste time if we are unsure we are adding (and supporting) the feature. Thanks.

**Comment by g7ed6e** [comment]
@brockallen you can assign to me

**Comment by leastprivilege** [comment]
We added this to our next milestone - which means we will definitely look into it. 

For us it is typically easier and less time consuming to just do the work ourselves than reviewing, testing, discussing and integrating external PRs. Thanks for the offer though!!!

**Comment by brockallen** [comment]
The general redirect response processing could use a revamp, but would cause a breaking change. If we support this, then I'd want to do it as part of that revamp.

**Comment by brockallen** [comment]
@g7ed6e, @filipw

When you use prompt=create today, do you ever use it with other prompt values? The spec only recommends you not do this, but I'm curious how you use it.

Also, @g7ed6e suggested adding a new property on the InteractionResponse to indicate create, and this implies a new URL on the UserInteraction. I wasn't going to do that in this version, and save major rework on the response processing until a major release. So this would mean for now we'd just redirect to the login URL with the prompt=create.

Thoughts?

**Comment by g7ed6e** [comment]
> @g7ed6e, @filipw
> 
> 
> 
> When you use prompt=create today, do you ever use it with other prompt values? The spec only recommends you not do this, but I'm curious how you use it.
> 
> 
> 
> Also, @g7ed6e suggested adding a new property on the InteractionResponse to indicate create, and this implies a new URL on the UserInteraction. I wasn't going to do that in this version, and save major rework on the response processing until a major release. So this would mean for now we'd just redirect to the login URL with the prompt=create.
> 
> 
> 
> Thoughts?

Today I'm not combining it with other prompts. I understand you prefer not to introduce a new URL until next major release but redirecting to login will I think break existing implementations which have different URLs for login and account creation. 
Could you let the Custom behavior be ran before this new prompt until next major release ? It will avoid breaking existing implementations before next major.

**Comment by brockallen** [comment]
> redirecting to login will I think break existing implementations which have different URLs for login and account creation.

But that's always been the design with any additional params (e.g. acr_values, etc). The login page is the one place to funnel all those requests and the GET implementation is expected to inspect the authorization context to then take the user to the correct place (either with another redirect or by dynamically showing the correct view).

And given that prompt=create does not currently exist (at least in IdentityServer itself), there should not be anyone using it today (without extensions/customizations).

**Comment by g7ed6e** [comment]
It would ease the update, at least in my case.

**Comment by brockallen** [comment]
Quick update here --

I updated the PR with what I think will be an ok compromise. There is a new `CreateAccountUrl` property on the `UserInteractionOptions` and it is `null` by default. If that is not set, then `prompt=create` is not enabled. You need to set that to your account create page to enable support. Once you do, then it will be allowed and enabled in discovery. We only support `create` by itself, so no mixing with other values.

Have a look at the code in the PR to see if you have any feedback on it. 

Also, I have always disliked our design of the multiple booleans on the InteractionResponse, and the need to check multiple flags for control flow processing like `if(IsError || IsLogin || etc.)`. But history is history and we can't easily change it now. So I wanted to provide some more general flag to indicate the general type of interaction response, so a new `InteractionResponseType` was added. Have a look to see if that's at all useful.

Thanks.

**Comment by leastprivilege** [comment]
> If that is not set, then prompt=create is not enabled.

What would happen if the `CreateAccountUrl` is not set, but the client sends `prompt=create` - will the request be rejected, or will the prompt parameter be available for manual parsing on the login page?

**Comment by brockallen** [comment]
> What would happen if the CreateAccountUrl is not set, but the client sends prompt=create - will the request be rejected, or will the prompt parameter be available for manual parsing on the login page?

Currently (before this PR), any unknown prompt values are presented, then we ignore the entire list of values and thus not set into our strongly typed `AuthorizationRequest` object mode, but the prompt value is available by reading the raw request parameters (e.g. on the login page). 

The new spec says we should issue an error if we encounter any unknown values, but for this PR I did not want to include that sort of behavioral change. So this PR keeps the current behavior for unknown values.

**Comment by brockallen** [comment]
@g7ed6e, @filipw

We merged the PR, so you should be able to test against our [dev builds](https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds). We will also have a preview out at some point.

Thanks.

**Comment by g7ed6e** [comment]
> @g7ed6e, @filipw
> 
> We merged the PR, so you should be able to test against our [dev builds](https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds). We will also have a preview out at some point.
> 
> Thanks.

@brockallen I tested to upgrade to 6.3.0-alpha.0.21 and it works great. Thanks!
