### ISSUE TITLE
Device flow always requests consent after user code capture, ignoring RequireConsent = false in client config

### ISSUE THREAD

**Issue by felinepc** [DuendeSoftware/IdentityServer#437]
**Which version of Duende IdentityServer are you using?**
5.2.3

**Which version of .NET are you using?**
5.0

**Describe the bug**

When the user is asked to go to the /device view to enter the `user_code` returned by the device authorization endpoint, the consent screen always shows up even though the client was configured with `RequireConsent = false`

**Expected behavior**

The `RequireConsent` setting should be honored as configured.

**Comment by brockallen** [comment]
That flag is only used for regular authorize requests. The device flow must always show a user what's at the verification URL to (at least) validate the user code. Our quickstart UI for that shows a consent screen (which is different then the normal consent UI), but you can change it in any way you want.

I will warn you -- not showing a verbose consent screen can be dangerous. Here's a great video showing how AAD's awful consent screen for device flow which allowed for users to be easily phished:

https://www.youtube.com/watch?v=9slRYvpKHp4

**Comment by mikequ-taggysoft** [comment]
@brockallen Wow thanks for the link to that video. I'm now thinking it's probably best to not use the device flow at all. 

From what I understood after watching it, in the sense of scope limitation, the Identity Server implementation is good: we can define a clear and restricted list of scopes the device client can do, so no lateral movement here.

But the "generating a code request from anywhere and then convincing the user to enter the code at the official URL " part is an inherent danger of the flow itself and there does not appear to be any practical remediation for it.

**Comment by brockallen** [comment]
Device flow is for a very specific scenario and yes the attack in that video is very concerning.

If you have a scenario where you have an interactive user and the client app is on the user's device (mobile/desktop) then code flow + PKCE with the system browser is the way to go.
