### ISSUE TITLE
More options for redirect_uri validation

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#44]
see 

https://github.com/IdentityServer/IdentityServer4/issues/4865

**Comment by leastprivilege** [comment]
e.g. with JAR and PAR the spec allows more flexibility in validation. As of today the validator does not have that context.

**Comment by brockallen** [comment]
The concern here is that passing the ValidatedRequest will only be partially populated based on where we perform URL validation. This means that only some of the context params are usable, but passing the whole ValidatedRequest seems confusing and too much. @leastprivilege

**Comment by brockallen** [comment]
Maybe it's sufficient to pass over the raw request collection and/or any RequestObjectValues collected at this point in time.

**Comment by bigheadedmonster** [comment]
The things we need are Parameters, RequestObjectValues (if signed) and client context. Seems like a good fit for a new/specialized context class? :=) (and consider putting in a RequestSigned : bool, helper property)

Those things together give much control and power, as you can decorate the duence client object using your other interfaces.

**Comment by brockallen** [comment]
Draft PR opened -- have a look to see if that's sufficient of if there's something else.

**Comment by bigheadedmonster** [comment]
Looks perfect :)
