### ISSUE TITLE
Clients store case sensitive?

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/IdentityServer#450]
Using Duende v5.2.3.

I have a client named `identityserver4-clientcredentials`.

If I try to retrieve a token passing `identityserver4-CLIENTCREDENTIALS`, I get the following error:

```
Duende.IdentityServer.Validation.ClientSecretValidator[0]
No client with id 'identityserver4-CLIENTCREDENTIALS' found. aborting
```

I believe the problem is with `DefaultCache<T>`. It should ignore casing and make it depend on the database collation (in case anyone really wants to have case sensitive configuration).

PS: Again, if `DefaultCache<T>.GetKey()` was virtual, I could at least provide a temporary fix. :(

**Comment by brockallen** [comment]
IIRC, we've always treated client ids, scope names, resource identifiers, etc. as case sensitive.

**Comment by brockallen** [comment]
[Client id](https://datatracker.ietf.org/doc/html/rfc6749#section-2.2) is a unique string, which [seems to me](https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.1) like it's case sensitive (given that different octets would be a different value).

 So if it worked in the past, then that feels like a bug.

**Comment by brockallen** [comment]
I think we're all in agreement that this should stay the way it is now, so I'll close. Thanks.
