### ISSUE TITLE
Nonce included in id token despite being forbidden by spec in at least some uses

### ISSUE THREAD

**Issue by ace90210** [DuendeSoftware/IdentityServer#460]
I found this issue while I am working on implementing BFF for the company i work for and as part of my research i implemented server side sessions and attempted to test revoking a logged in user.

Before i continue this isnt an issue with BFF but it provides an example of why this is an issue and is how i came across it.

After getting everything setup correctly i get the error 
`Back-channel logout error. error: 'Logout token should not contain nonce claim.'|`

When i checked there is indeed a nonce claim included and when i tested the sample Identity Server (both 4.1.2 and Duende 5.2.2), i found this is normal and included behaviour (i dont know how to disable it either).

This doesnt appear to be correct however as according to the spec (see [here](https://openid.net/specs/openid-connect-backchannel-1_0.html))  i found the nonce is **banned** from jwt id tokens for security reasons (at least when logging out)

This seems to either be a security bug, **or** needs documenting how we are supposed to convert a id token that has a nonce  claim to one that does not. 

As it stands this is blocking me being able to test BFF revocation using the backchannel endpoint because the only id token i have access to includes the nonce claim

**Comment by leastprivilege** [comment]
For logout you are not using an id_token. but a logout token. This logout token is generated by IdentityServer automatically at logout time when a `BackChannelLogoutUri` is configured for the client.

Could you describe in more detail how and under which circumstances this error occurs?
