### ISSUE TITLE
Home Page shows 'Refused to connect to... violates Content Security Policy directive' Error in console

### ISSUE THREAD

**Issue by marqdouj** [DuendeSoftware/IdentityServer#468]
**Which version of Duende IdentityServer are you using?**
5.2.1

**Which version of .NET are you using?**
netcoreapp3.1
Windows 11
Microsoft Edge

**Describe the bug**
This StackOverflow issues describes the bug:
https://stackoverflow.com/questions/68269276/how-can-fix-it-violates-the-following-content-security-policy-directive-defau

**To Reproduce**
Complete the quickstart up to:
https://docs.duendesoftware.com/identityserver/v5/quickstarts/2_interactive/

Then run the service and display the home page.

![IdentityServerHomePage](https://user-images.githubusercontent.com/16510416/137606989-5cf8a2a6-47ef-4af5-b729-d614ace66a67.png)

**Comment by leastprivilege** [comment]
Both errors come from scripts injected by Visual Studio. Do they cause any runtime problems besides the error message?

**Comment by marqdouj** [comment]
Hi Dominick,

Everything seems to work just fine. I noticed the errors so I thought I would let you know (I am new to web development so  I wasn’t sure what was causing the error).

Thanks,

Doug Marquardt

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by brockallen** [comment]
Yea, the short answer is "don't use browser link", or "update the CSP to allow browser link", depending on if you want to use it. Personally, I do the former.
