### ISSUE TITLE
Authorization Code flow barfs with null pointer exception

### ISSUE THREAD

**Issue by mmacagno** [DuendeSoftware/IdentityServer#473]
**Which version of Duende IdentityServer are you using?**
5.2.3

**Which version of .NET are you using?**
.NET 5.0

**Describe the bug**
Aspnet MVC website (running on DOTNETCORE 3.1) authenticating against identity provider via authorization code.
Identity provider just migrated to Duende.
Aspnet MVC website using https://github.com/IdentityModel/IdentityModel 4.2

When connecting to the aspnet MVC website (unauthenticated) I get redirected to the authorization endpoint:

https://{endpoint}/connect/authorize?client_id={client_id}&redirect_uri={redirectURI}&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0

The identity server barfs with this exception: Object reference not set to an instance of an object.

**To Reproduce**

It repros with all my authorization code clients. Not sure how to specify repro steps for you sorry.

**Expected behavior**

login page displayed. This flow is properly working with identity server, and stopped working after migrating to Duende.
I followed the migration steps, which are straightforward, not sure what I may have messed up.

**Log output/exception with stacktrace**

```
{
"type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
"title": "Object reference not set to an instance of an object.",
"status": 500,
"detail": "Object reference not set to an instance of an object.:    at Duende.IdentityServer.Extensions.StringExtensions.AddQueryString(String url, String query) in /_/src/IdentityServer/Extensions/StringsExtensions.cs:line 196\r\n   at Duende.IdentityServer.Extensions.StringExtensions.AddQueryString(String url, String name, String value) in /_/src/IdentityServer/Extensions/StringsExtensions.cs:line 211\r\n   at Duende.IdentityServer.Endpoints.Results.LoginPageResult.ExecuteAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/Results/LoginPageResult.cs:line 77\r\n   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103\r\n   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103\r\n   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48\r\n   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 32\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)",
"traceId": "00-580edba24fed2141ba9027b94c9a00f7-11604a00ae72514a-00"
}
```

**Additional context**

The line on which it barfs is here. how can url be null being an extension method? 

![image](https://user-images.githubusercontent.com/2315384/137829083-5cf52e48-108c-42d4-968c-f25bd6236204.png)

**Comment by mmacagno** [comment]
Going one step further, the url is prepared in LoginPageResult.cs:

![image](https://user-images.githubusercontent.com/2315384/137986017-f4423789-aa4d-4ad8-8f9f-11667619764b.png)

Even if IServerUrls >> _urls was null, returnUrl should not be null. I don't understand how and why this is breaking.

Any clue?

**Comment by brockallen** [comment]
Hi, thanks for the report. We'll investigate.

**Comment by mmacagno** [comment]
It was in the initial report, anyway, here it is again:

Duende.IdentityServer.Extensions.StringExtensions.AddQueryString(String url, String query) in /_/src/IdentityServer/Extensions/StringsExtensions.cs:line 196\r\n   at Duende.IdentityServer.Extensions.StringExtensions.AddQueryString(String url, String name, String value) in /_/src/IdentityServer/Extensions/StringsExtensions.cs:line 211\r\n   at Duende.IdentityServer.Endpoints.Results.LoginPageResult.ExecuteAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/Results/LoginPageResult.cs:line 77\r\n   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103\r\n   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103\r\n   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48\r\n   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 32\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"

**Comment by mmacagno** [comment]
One oddity that might be a red herring but...

I tried to inject IServerUrls in a TestController to inspect it at runtime and it breaks the build.
Am I missing some references / nuget packages?

![image](https://user-images.githubusercontent.com/2315384/138186702-2cda6ea5-6a15-481e-b298-87dc82eeb69d.png)

![image](https://user-images.githubusercontent.com/2315384/138186803-1f5eaa7a-46c7-4c12-a4c2-11d1ae22f5a4.png)

thanks
mac

**Comment by mmacagno** [comment]
So I injected the options in a TestController, and indeed LoginUrl is null.

![image](https://user-images.githubusercontent.com/2315384/138188612-d3c1aab1-3281-420d-a384-56ffd5c80944.png)

So I went back and added these two values to the options **and it now works.**

![image](https://user-images.githubusercontent.com/2315384/138189842-e8f3d8b5-fd56-4a1e-91d6-c048cb553652.png)

I did not do that in IS4, I think it had a default. Is that no longer the case in Duende.IdentityServer?

I'm leaving to you to decide if this is a bug or by design and close accordingly.
Thanks for the insightful questions, you put me on the right track!

mac

**Comment by mmacagno** [comment]
> For the `LoginUrl`, are you setting the `LoginPath` on the `CookieAuthenticationOptions` anywhere?

No, the only place where that path is set is here (Startup.cs, before IdentityServer is added to the services):

```
            services.AddRazorPages(options =>
            {
                options.Conventions.AddPageRoute("/Identity/Account/Login", "/");
            });
```

**Comment by brockallen** [comment]
Any update on this @mmacagno, or can we close this issue?

**Comment by mmacagno** [comment]
I haven't got around to investigate this yet, it's still an issue. Please leave it open a little longer.
Will give an update ASAP.

**Comment by mmacagno** [comment]
Related conversation https://github.com/DuendeSoftware/IdentityServer/discussions/483
Finally resolved.
Closing.
