### ISSUE TITLE
Random 490 status code failures with automatic key management

### ISSUE THREAD

**Issue by nathanvv** [DuendeSoftware/IdentityServer#474]
We are using Duende IdentityServer 5.2.3 with .net 5

Followed the following documentation to migrate to automatic key management https://docs.duendesoftware.com/identityserver/v5/upgrades/is4_v4_to_dis_v5/#step-5-migrating-signing-keys-optional 

Based on the above documentation, removed AddSigningCredential() and restarted the API client. 

The client for this application uses resource owner password flow and this is how we have set up token validation in the API gateway

![image](https://user-images.githubusercontent.com/11080029/138043680-5c02316f-3425-4c46-8271-c675cedf9b75.png)

**Issue**: Every 8 out of 10, the API request errors with a 490 status code. We enabled the PII to get more information by setting 
`IdentityModelEventSource.ShowPII = true;  `
The error says the keys are a mismatch. But when comparing the keys manually, they are the same. 

Works fine when we disable automatic key management by adding 
`                    options.KeyManagement.Enabled = false;
`
and setting 
`    .AddSigningCredential(GET_CERT_FROM_VAULT)
`

**Comment by brockallen** [comment]
@nathanvv did you make any progress or were you able to get any more detailed logs?
