### ISSUE TITLE
Extend to allow passing UserAccessTokenParameters to GetUserAccessTokenAsync

### ISSUE THREAD

**Issue by darrenschwarz** [DuendeSoftware/IdentityServer#482]
### Discussed in https://github.com/DuendeSoftware/IdentityServer/discussions/481

<div type='discussions-op-text'>

<sup>Originally posted by **darrenschwarz** October 21, 2021</sup>
Motivation is to allow for the use of Duende.Bff in a project requiring the use of multiple authentication schemes, and storage of multiple API-specific tokens.

UserAccessTokenParameters are already exposed on: Assembly IdentityModel.AspNetCore, TokenManagementHttpContextExtensions

See: https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/7a5c695fab848dcfffc790d57abd03eb9c254a93/src/AccessTokenManagement/TokenManagementHttpContextExtensions.cs#L24

This is a non-breaking change, and as such all tests pass unchanged.

I have forked and committed here: https://github.com/darrenschwarz/BFF/commit/ccbd91ddf8bcbbe8736afc973c507202b5642625

We are already an enterprise customer of Duende, so already fully bought in. If you think this makes sense and would consider me making a PR that would be great, and would mean we don't have to maintain a separate project.

Look forward to hearing back. </div>

**Comment by leastprivilege** [comment]
Next week I will have some time to look into this...

**Comment by leastprivilege** [comment]
So I had a brief look - 

I can see the motivation - I am not happy with making an IdentityModel API a top-level API in BFF - I also do not like 

```cs
if (!string.IsNullOrEmpty(userAccessTokenParameters.SignInScheme))
{
   var result = await context.AuthenticateAsync(userAccessTokenParameters.SignInScheme);
                           
   //see for derivation of .AuthScheme https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.
  userAccessTokenParameters.ChallengeScheme = result?.Properties?.Items[".AuthScheme"]; 
}
```

Let's think about a more elegant way...

**Comment by darrenschwarz** [comment]
Thank you that's constructive feedback. The code you mention above was admittedly on account of it fitting with my current scenario, and allowed me to express the initial intention to you. Let me give some thought, and get back to you, either with some inspired suggestion :), though possibly a question or two. Would you be available at all to discuss on a call?

**Comment by darrenschwarz** [comment]
> So I had a brief look -
> 
> I can see the motivation - I am not happy with making an IdentityModel API a top-level API in BFF - I also do not like
> 
> ```cs
> if (!string.IsNullOrEmpty(userAccessTokenParameters.SignInScheme))
> {
>    var result = await context.AuthenticateAsync(userAccessTokenParameters.SignInScheme);
>                            
>    //see for derivation of .AuthScheme https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.
>   userAccessTokenParameters.ChallengeScheme = result?.Properties?.Items[".AuthScheme"]; 
> }
> ```
> 
> Let's think about a more elegant way...

@leastprivilege  Hopefully we are thinking on similar lines. Look forward to feedback. 

`public static class BffRemoteApiEndpoint
    {
        private const string AuthSchemeKey = ".AuthScheme";

...

UserAccessTokenParameters paramsCopied = new UserAccessTokenParameters();

                    if (metadata.BffUserAccessTokenParameters != null && !string.IsNullOrEmpty(metadata.BffUserAccessTokenParameters.SignInScheme))
                    {
                        paramsCopied.Resource = metadata.BffUserAccessTokenParameters.Resource;
                        paramsCopied.SignInScheme = metadata.BffUserAccessTokenParameters.SignInScheme;
                        paramsCopied.ForceRenewal = metadata.BffUserAccessTokenParameters.ForceRenewal;
                   
                        var result = await context.AuthenticateAsync(metadata.BffUserAccessTokenParameters.SignInScheme);
                        if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
                        {
                            paramsCopied.ChallengeScheme = authenticatedScheme;
                        }
                    }`

Also to address top level API comment

`.WithUserAccessTokenParameter(new BffUserAccessTokenParameters("cookies", null, false, Constants.Auth.ApiResources.CdpApi))

...

/// <summary>
        /// Allows for setting a UserAccessTokenParameter
        /// </summary>
        /// <param name="builder"></param>
        /// <param name="bffUserAccessTokenParameters"></param>
        /// <typeparam name="TBuilder"></typeparam>
        /// <returns></returns>
        public static TBuilder WithUserAccessTokenParameter<TBuilder>(this TBuilder builder, BffUserAccessTokenParameters bffUserAccessTokenParameters) where TBuilder : IEndpointConventionBuilder
        {
            builder.Add(endpointBuilder =>
            {
                var metadata =
                    endpointBuilder.Metadata.First(m => m.GetType() == typeof(BffRemoteApiEndpointMetadata)) as BffRemoteApiEndpointMetadata;

                metadata.BffUserAccessTokenParameters = bffUserAccessTokenParameters;
            });

            return builder;
        }
`

**Comment by leastprivilege** [comment]
```cs
 if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
```

Why can't you simply set the signin and challenge scheme explicitly? Interacting with the asp.net core authN system is not a concern at this point in the code.

**Comment by darrenschwarz** [comment]
> ```cs
>  if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
> ```
> 
> Why can't you simply set the signin and challenge scheme explicitly? Interacting with the asp.net core authN system is not a concern at this point in the code.

**Comment by darrenschwarz** [comment]
> > ```cs
> >  if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why can't you simply set the signin and challenge scheme explicitly? Interacting with the asp.net core authN system is not a concern at this point in the code.

**Comment by darrenschwarz** [comment]
So if I understand the question corrdctly, you could set explicitly but that wouldn't preclude the need for passing in the UserAccessTokenParameter as this has additional motivation such as the ability to set forcerenewal.

**Comment by darrenschwarz** [comment]
> ```cs
>  if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
> ```
> 
> Why can't you simply set the signin and challenge scheme explicitly@leastprivilege
@darrenschwarz
@darrenschwarz
 
darrenschwarz commented 17 days ago
Discussed in #481
Originally posted by darrenschwarz October 21, 2021
Motivation is to allow for the use of Duende.Bff in a project requiring the use of multiple authentication schemes, and storage of multiple API-specific tokens.

UserAccessTokenParameters are already exposed on: Assembly IdentityModel.AspNetCore, TokenManagementHttpContextExtensions

See: https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/7a5c695fab848dcfffc790d57abd03eb9c254a93/src/AccessTokenManagement/TokenManagementHttpContextExtensions.cs#L24

This is a non-breaking change, and as such all tests pass unchanged.

I have forked and committed here: darrenschwarz/BFF@ccbd91d

We are already an enterprise customer of Duende, so already fully bought in. If you think this makes sense and would consider me making a PR that would be great, and would mean we don't have to maintain a separate project.

Look forward to hearing back.

@leastprivilege leastprivilege self-assigned this 9 days ago
@leastprivilege
 
Contributor
leastprivilege commented 9 days ago
Next week I will have some time to look into this...

@leastprivilege leastprivilege assigned brockallen 8 days ago
@leastprivilege
 
Contributor
leastprivilege commented 4 days ago
So I had a brief look -

I can see the motivation - I am not happy with making an IdentityModel API a top-level API in BFF - I also do not like

if (!string.IsNullOrEmpty(userAccessTokenParameters.SignInScheme))
{
   var result = await context.AuthenticateAsync(userAccessTokenParameters.SignInScheme);
                           
   //see for derivation of .AuthScheme https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.
  userAccessTokenParameters.ChallengeScheme = result?.Properties?.Items[".AuthScheme"]; 
}
Let's think about a more elegant way...

@darrenschwarz
 
Author
darrenschwarz commented 4 days ago • 
Thank you for your constructive feedback. The code you mention above was admittedly because it fits with my current scenario and wants to express the initial intention to you. Let me give some thought and get back to you with a suggestion; we'll see if I'm on the same track.

@darrenschwarz
 
Author
darrenschwarz commented 2 days ago • 
So I had a brief look -

I can see the motivation - I am not happy with making an IdentityModel API a top-level API in BFF - I also do not like

if (!string.IsNullOrEmpty(userAccessTokenParameters.SignInScheme))
{
   var result = await context.AuthenticateAsync(userAccessTokenParameters.SignInScheme);
                           
   //see for derivation of .AuthScheme https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.
  userAccessTokenParameters.ChallengeScheme = result?.Properties?.Items[".AuthScheme"]; 
}
Let's think about a more elegant way...

@leastprivilege Hopefully we are thinking on similar lines. Look forward to feedback.

var toUserAccessTokenParameters = new UserAccessTokenParameters();

                    if (metadata.BffUserAccessTokenParameters != null)
                    {
                        toUserAccessTokenParameters = metadata.BffUserAccessTokenParameters.ToUserAccessTokenParameters();

                        if (toUserAccessTokenParameters.SignInScheme != null)
                        {
                            var result = await context.AuthenticateAsync(toUserAccessTokenParameters.SignInScheme);
                            if (result.Properties != null &&
                                result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
                            {
                                toUserAccessTokenParameters.ChallengeScheme = authenticatedScheme;
                            }
                        }
                    }
Also to address top-level API comment

public static TBuilder WithUserAccessTokenParameter<TBuilder>(this TBuilder builder, BffUserAccessTokenParameters bffUserAccessTokenParameters) where TBuilder : IEndpointConventionBuilder
        {
            builder.Add(endpointBuilder =>
            {
                var metadata =
                    endpointBuilder.Metadata.First(m => m.GetType() == typeof(BffRemoteApiEndpointMetadata)) as  BffRemoteApiEndpointMetadata;

                metadata.BffUserAccessTokenParameters = bffUserAccessTokenParameters;
            });

            return builder;
        }
@leastprivilege
 
Contributor
leastprivilege commented 16 hours ago
 if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
Why can't you simply set the signin and challenge scheme explicitly? Interacting with the asp.net core authN system is not a concern at this point in the code.

@darrenschwarz darrenschwarz closed this 10 hours ago
@darrenschwarz darrenschwarz reopened this 10 hours ago
@darrenschwarz

 
 
🤗
> ```cs
>  if (result.Properties != null && result.Properties.Items.TryGetValue(AuthSchemeKey, out var authenticatedScheme))
> ```
> 
> Why can't you simply set the signin and challenge scheme explicitly? Interacting with the asp.net core authN system is not a concern at this point in the code.

@leastprivilege, Absolutely see your point. Please see the latest commit: https://github.com/darrenschwarz/BFF/commit/6ab58d50c4d63955283480b5377fd2a2d005b44d 
? Interacting with the asp.net core authN system is not a concern at this point in the code.

@leastprivilege, Absolutely see your point. Please see the latest commit: https://github.com/darrenschwarz/BFF/commit/6ab58d50c4d63955283480b5377fd2a2d005b44d 

Comment: "Removed setting schemes out from BffRemoteApiEndpoint, now handled by the implementation of IUserAccessTokenManagementService. Leaving the crucial part; carrying through the UserAccessTokenParameters set at the time of endpoint configuration.".

**Comment by leastprivilege** [comment]
yep. looks better to me.

I will start working on BFF 1.1 later/tomorrow - then we can do a clean PR

**Comment by darrenschwarz** [comment]
> yep. looks better to me.
> 
> I will start working on BFF 1.1 later/tomorrow - then we can do a clean PR

That's awesome! Thank you for the guidance through this. I'll keep an eye out.

**Comment by darrenschwarz** [comment]
> yep. looks better to me.
> 
> I will start working on BFF 1.1 later/tomorrow - then we can do a clean PR

@leastprivilege any movement on this, I don't mean to rush at all just looking t plan work load.

**Comment by leastprivilege** [comment]
do you want to do a PR now that main is updated. Then we can discuss there.

**Comment by leastprivilege** [comment]
Update pushed.
