### ISSUE TITLE
CreateJwtPayloadDictionary: Expecting parsing custom claim by claim valueType

### ISSUE THREAD

**Issue by thohng** [DuendeSoftware/IdentityServer#49]
**Which exact version are you using?**
5.0.0-preview.2.13

**Describe the bug**

Currently implementation parsing value object by claimName (claim.Type)
https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/TokenExtensions.cs#L132-L155

**Comment by leastprivilege** [comment]
merged. thanks!
