### ISSUE TITLE
CorsPolicyService warns of unallowed origin even though it is set and request goes through

### ISSUE THREAD

**Issue by BrunoBlanes** [DuendeSoftware/IdentityServer#491]
## Bug
I get the following warning from Duende IdentityServer's CorsPolicyProvider in the console:
```
Duende.IdentityServer.Hosting.CorsPolicyProvider[0]
CorsPolicyService did not allow origin: https://jwt.io
```

### Startup.cs
```c#
public void ConfigureServices(IServiceCollection services)
{
    [...]

    services.AddCors(options =>
    {
	options.AddDefaultPolicy(builder =>
	{
	    builder.WithOrigins("https://jwt.io");
	});
    });
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    
    app.UseIdentityServer();
    app.UseRouting();
    app.UseCors();
}
```

## Expected Behavior
I expected a waning not to be printed on the console if I explicitly allowed said domain. An informational log message would be ok, as long as it printed something in the lines of "said origin was allowed".

## Additional Information
As you can see in this image below, the header is set and the request goes though, however I still get a warning on my console saying otherwise.

![image](https://user-images.githubusercontent.com/28227097/139598010-c678868c-f1d5-4826-bbc2-d06253977a3c.png)

## Versions
**Duende IdentityServer:** 6.0.0-preview.2
**ASP.NET:** 6.0.100-rc.2.21505.57

**Comment by brockallen** [comment]
Can you provide a summary of the HTTP request (method, path, and headers) that log entry is being made for? I can tell you that Chrome sends the Origin header for most POST requests (despite them not being Ajax calls), so the server has a hard time knowing the difference.

**Comment by BrunoBlanes** [comment]
Hy @brockallen, I'm sorry I don't quite follow you. I was trying to validade a JWT on https://jwt.io and the website requested the OpenID configuration endpoint.

**Comment by brockallen** [comment]
I wanted to see the HTTP request details for the request where that log is being emitted. 

But then also, why is jwt.io making calls to IdentityServer then? I'm confused.

**Comment by BrunoBlanes** [comment]
jwt.io makes the call to validade the JWT signature using the token issuer's address.

**Comment by brockallen** [comment]
Maybe they're making that request from the browser? So you would need to allow CORS for them?

**Comment by BrunoBlanes** [comment]
Yes, they are, but haven't I done that?

**Comment by brockallen** [comment]
So then add them to the allowed cors origins for the client to allow them to make that request?

**Comment by BrunoBlanes** [comment]
According to this [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0#set-the-allowed-origins), by implementing the following lines of code CORS should be allowed, am I not right?
```c#
public void ConfigureServices(IServiceCollection services)
{
    [...]

    services.AddCors(options =>
    {
	options.AddDefaultPolicy(builder =>
	{
	    builder.WithOrigins("https://jwt.io").SetIsOriginAllowedToAllowWildcardSubdomains();
	});
    });
}
```

**Comment by brockallen** [comment]
According to our [docs](https://docs.duendesoftware.com/identityserver/v5/tokens/cors/), no :)

**Comment by BrunoBlanes** [comment]
Oh, so IdentityServer doesn't make use of the default ASP.NET CORS policies?

**Comment by BrunoBlanes** [comment]
I just read the post and yeah, it seems so:

> IdentityServer implements its own custom ICorsPolicyProvider and registers it in the DI system.

I'll implement that and try it out, but in the mean time, why does it implements its own ICorsPolicyProvider?

**Comment by brockallen** [comment]
> why does IdentityServer implements its own ICorsPolicyProvider?

Because we know about all of our endpoints that might require CORS, and we provide an abstraction to enable it for the clients that need it via the `Client` config.

**Comment by BrunoBlanes** [comment]
Cool, makes sense. Thanks for your time, it seems to work just fine using your implementation of it, so I'll just close this issue.
