### ISSUE TITLE
Remove "openid" OidcProvider's Scopes collection

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#493]
It's being added automatically, and doesn't allow someone that needs to opt-out of it in case an upstream IdP doesn't allow it (for some reason).

**Comment by leastprivilege** [comment]
An OIDC provider that does not support the `openid` scope?

**Comment by brockallen** [comment]
> An OIDC provider that does not support the openid scope?

Well, Ping federate it's optional, per-client opt-in. Go figure.

**Comment by leastprivilege** [comment]
lol

**Comment by brockallen** [comment]
Also, oddly enough they implement CIBA and PAR, but not PKCE AFAICT. More **\*shrug***.
