### ISSUE TITLE
New CachingResourceStore breaks requested resources validation

### ISSUE THREAD

**Issue by sebastienlescure** [DuendeSoftware/IdentityServer#523]
**Which version of Duende IdentityServer are you using?**
6.0.0-preview.3 (6.0.0-preview.1 does not have the problem)

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

Upgrading from 6.0.0-preview.1 to 6.0.0-preview.3 broke the capability to obtain an authorization code right after server starts.

**To Reproduce**

* Declare a resource store that has no identity scope, but some api scopes and api resources.
* Declare a client using authorization code flow, and allowed from some api scopes.
* Start the server.
* Send an authorization request for the client as the first HTTP request to the server.
* Requests fails with log : "Scope XXX not found in store or not supported by requested resource indicators."

**Expected behavior**

Authorization code should be obtained.

**Log output/exception with stacktrace**

fail: Duende.IdentityServer.Validation.DefaultResourceValidator[0]
      Scope XXX not found in store or not supported by requested resource indicators.
fail: Duende.IdentityServer.Endpoints.AuthorizeEndpoint[0]
      Request validation failed

**Additional context**

I made some search on the problem, and succeeded in "kind of" fixing it, but I'm not sure my fix would work in all cases :
* Problem origin comes from the call to FindEnabledResourcesByScopeAsync in DefaultResourceValidator
* FindEnabledResourcesByScopeAsync tries to find resources for the requested scopes in the following order : Identity Resources, Api Resources, Api Scopes.
* The CachingResourceStore will at first find nothing for Identity Resources, and generate an "empty" cache in the _allCache collection with a key associated with the requested scopes, and no prefix (CachingResourceStore line 139).
* When coming to the same search for Api Scopes, the CachingResourceStore will fetch the "empty" cache that was set for Identity resources because it generates the same exact itemsKey (No prefix, same list of scopes).

Adding a keyPrefix for each domain seems to fix the problem.

**Comment by brockallen** [comment]
Thanks for this! We'll have a look.

**Comment by brockallen** [comment]
I was able to repro the issue and your assessment was spot on, and I came to the same fix you have proposed. PR submitted. Feel free to test against our nightly builds to ensure it's working. We'll see if we can get a preview out.

**Comment by sebastienlescure** [comment]
Great news. Where can I find the nightly build if I want to test ? Ready your commit, I think the fix is OK anyway.

**Comment by brockallen** [comment]
> Where can I find the nightly build if I want to test

https://docs.duendesoftware.com/identityserver/v5/overview/packaging/#dev-builds

**Comment by sebastienlescure** [comment]
I may be bugging but I can't seem to find any newer version than 6.0.0-preview.4 from the feed :).
Anyway, we are sticking to 6.0.0-preview.1 on our development environment waiting for release, no urgency for a new preview.

**Comment by brockallen** [comment]
Hmm, yea, I don't either. Ping @leastprivilege
