### ISSUE TITLE
Breaking change in System.IdentityModel.Tokens.Jwt 5.6.0 -> 6.5.0

### ISSUE THREAD

**Issue by jaanclaeys** [DuendeSoftware/IdentityServer#538]
If you are referencing the nuget package Duende.IdentityServer from a netcoreapp3.1, and you are doing stuff with this package System.IdentityModel.Tokens.Jwt with a higher version than 5.6.0  in your pojrect itself. It throws exceptions at runtime , because the identityserver uses the TokenValidationResult in Microsoft.IdentityModel.JsonWebTokens.
See [Release notes  of this package](https://github.com/azuread/azure-activedirectory-identitymodel-extensions-for-dotnet/releases?page=2)

The real reference of course at time of creation of the nuget package: 
Microsoft.AspNetCore.Authentication.OpenIdConnect Lowest version compatible is 3.1.0
=> References Microsoft.IdentityModel.Protocols.OpenIdConnect, lowest version 5.5.0
=> References System.IdentityModel.Tokens.Jwt, lowest version 5.5.0

I do not know if I can get passed around this locally actually.
Solution might be to reference Microsoft.IdentityModel.Protocols.OpenIDConnect 6.5.0 directly for aspnetcore3.1 on the Duende.IdentityServer.csproj ?

This hinders actually using new features of that library.
It might also hinder upcoming security updates to this library., and in effect it is kind of the heart for introspection, client authentication with jwt and local validation.

Of course you could ignore this issue until 3.1 support goes away as well.

**Comment by leastprivilege** [comment]
Yes - the MS.IdentityModel versions are not compatible. It's a pain point for all of us.

**Comment by brockallen** [comment]
Closing since there's no action item here for us.
