### ISSUE TITLE
Database ApiScopes table NonEditable and Created columns conflict

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [DuendeSoftware/IdentityServer#592]
I'm building and populating an IdentityServer database using the sql scripts here: https://github.com/DuendeSoftware/IdentityServer/tree/main/migrations/IdentityServerDb/Migrations

And I'm using the InitializeDatabase method in the quickstart outlined here:  https://docs.duendesoftware.com/identityserver/v5/quickstarts/4_ef/

I'm getting an error because the ApiScopes table doesn't allow nulls for the NonEditable and Created columns.  

The error I'm getting for the NonEditable column (which is similar to the Created column) is: 

_SqlException: Cannot insert the value NULL into column 'NonEditable', table '_[xxx]_.dbo.ApiScopes'; column does not allow nulls. INSERT fails._

It appears there is a conflict between the database script provided and the EF models for the ApiScopes entity.

**Comment by brockallen** [comment]
> I'm building and populating an IdentityServer database using the sql scripts here: https://github.com/DuendeSoftware/IdentityServer/tree/main/migrations/IdentityServerDb/Migrations

We recommend that you build your own migrations and SQL scripts, as our docs walk you thru. Try this please, and see if you have errors/issues.

The scripts and project you link above are samples (mainly to show how you could manage creating those scripts), and they are used by us during development. You might be looking at the latest code, which is likely newer than the version of our latest released NuGet (or the version from the quickstart), so that might explain mismatches.

**Comment by rasaconsulting-sandy** [comment]
So to confirm, I should be using the Dunede templates to build my IdentityServer and not the samples - correct?  Also I should be using V5 and not V6 yet (I think I've confirmed this previously but just checking to be 100% sure).

To build my migrations I will follow this:
https://docs.duendesoftware.com/identityserver/v5/quickstarts/4_ef/

**Comment by brockallen** [comment]
> So to confirm, I should be using the Dunede templates to build my IdentityServer and not the samples - correct

Well, however you get the EF code into your project, it's recommended you build your own scripts. Also, the SQL is always provider specific, so whatever DB we are using for testing might not be the same DB you're using. 

v5 is the current released version, v6 will be released Jan 2022. You can use the v6 preview, though, if you'd like. That might be better, to be honest, if you don't plan to release until after January.

**Comment by rasaconsulting-sandy** [comment]
Ok thanks again Brock.  I'll use v6 preview as I'm releasing after January.  I appreciate your help!  Best wishes for the festive season.  Sandy

**Comment by brockallen** [comment]
I have updated the docs in our v6 release to better explain this. Thanks.

**Comment by rasaconsulting-sandy** [comment]
Thanks Brock - I appreciate it.
