### ISSUE TITLE
Multiple URL Encoding

### ISSUE THREAD

**Issue by markrendle** [DuendeSoftware/IdentityServer#636]
**Which version of Duende IdentityServer are you using?**

6.0.0-preview.3

**Which version of .NET are you using?**

6.0.1

**Describe the bug**

Double-encoding of URL parameters is triggering an OWASP violation in Azure WAF.

When navigating to `/Account/Login` the `ReturnUrl` parameter is set to `/connect/authorize/callback?...`

The problem is this parameter is encoded to `%2Fconnect%2Fauthorize%2Fcallback%3F...`

And that return URL includes the `redirect_uri` parameter from that original `/connect/authorize/callback?` URI, which was
already `http://localhost:4200/index.html` encoded to `http%3A%2F%2Flocalhost%3A4200%2Findex.html`
and now gets encoded again to `http%253A%252F%252Flocalhost%253A4200%252Findex.html`.

**To Reproduce**

Run IdentityServer with ASP.NET Core Identity integration behind Azure WAF.

**Expected behavior**

Ideally IdentityServer should work with Azure WAF

**Log output/exception with stacktrace**

This is the event from Azure WAF

```
{
    "timeStamp": "2022-01-04T17:11:26+00:00",
    "resourceId": "/SUBSCRIPTIONS/ED0A31CD-260B-463B-BAA1-267FA2E7C1BA/RESOURCEGROUPS/FILEANDSERVEXPRESS-DEV1/PROVIDERS/MICROSOFT.NETWORK/APPLICATIONGATEWAYS/FILEANDSERVEXPRESS-DEV1-AGW",
    "operationName": "ApplicationGatewayFirewall",
    "category": "ApplicationGatewayFirewallLog",
    "properties": {
        "instanceId": "appgw_0",
        "clientIp": "67.250.253.130",
        "requestUri": "\/Account\/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dcode%26client_id%3Defsp%26state%3DRFNUMGVSLmZnUlpkajV2VXNBdHd3NG5kQ0s3blY5R2JHWVgxMk5fQjkzb3lV%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A4200%252Findex.html%26scope%3Dopenid%2520profile%2520organization%2520efsp%2520offline_access%26code_challenge%3DPeTx8S-OrnNgV2O8yM1KY06RMBJgzTo55M7p_v-ufb0%26code_challenge_method%3DS256%26nonce%3DRFNUMGVSLmZnUlpkajV2VXNBdHd3NG5kQ0s3blY5R2JHWVgxMk5fQjkzb3lV",
        "ruleSetType": "OWASP",
        "ruleSetVersion": "CRS 3.2",
        "ruleId": "920230",
        "ruleGroup": "REQUEST-920-PROTOCOL-ENFORCEMENT",
        "message": "Multiple URL Encoding Detected",
        "action": "Matched",
        "details": {
            "message": "Pattern match \\\\%\\\\w at ARGS.",
            "data": "\/connect\/authorize\/callback?response_type=code\\u0026client_id=efsp\\u0026state=RFNUMGVSLmZnUlpkajV2VXNBdHd3NG5kQ0s3blY5R2JHWVgxMk5fQjkzb3lV\\u0026redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Findex.html\\u0026scope=openid%20profile%20organization%20efsp%20offline_access\\u0026code_challenge=PeTx8S-OrnNgV2O8yM1KY06RMBJgzTo55M7p_v-ufb0\\u0026code_challenge_method=S256\\u0026nonce=RFNUMGVSLmZnUlpkajV2VXNBdHd3NG5kQ0s3blY5R2JHWVgxMk5fQjkzb3lV",
            "file": "REQUEST-920-PROTOCOL-ENFORCEMENT.conf",
            "line": "1099"
        },
        "hostname": "identity.dev.fileandserve.com",
        "transactionId": "c70960b451c56124b1478c82b3e01359",
        "policyId": "302#default",
        "policyScope": "Global",
        "policyScopeName": "Global",
        "engine": "Azwaf"
    }
},
```

**Additional context**

Maybe the `redirect_uri` parameter could be encoded a different way when constructing that `ReturnUrl` parameter? Base64 or something?

**Comment by markrendle** [comment]
A little further investigation revealed that the proper solution to this is probably to use the `IDistributedCache` method for storing OIDC state instead of the URL-encoding method. But maybe the URL-encoding method could be changed to use base64 encoding for the state instead of multiple query parameters?

**Comment by brockallen** [comment]
>Describe the bug
> Double-encoding of URL parameters is triggering an OWASP violation in Azure WAF.

This isn't the repo for the Azure WAF -- you'd need to ping them for their bug :)

Ok, joking aside. Yes, this has come up before. The problem is that the returnUrls (by design) might themselves have URLs in them, and as you've seen they will when the returnUrl is the authorize endpoint with its own redirect_uri query param. And in fact, this design is true for any login page with a returnUrl written in the past 20 years or so. My point is that I don't think this is specific to IdentityServer. 

If you want to change the returnURL to some encoded state param that your login page then has to do special processing to then redirect back to once the login is complete, rather than use the value as-is. But I don't think we want to go that way by default.

What people have done in the past is disable that rule in the WAF. With other WAFs you can disable the rule for specific endpoints, but I believe Azure is not sufficiently flexible and can only be done for the entire site.

If you don't want to disable the WAF rule, then you can register a `IAuthorizationParametersMessageStore` in DI, and then leverage the `IIdentityServerInteractionService.GetAuthorizationContextAsync` on your login page. But then your returnUrl is now this special state param (as opposed to a traditional returnURL).

HTH

**Comment by markrendle** [comment]
Thanks @brockallen - I've enabled the Distributed Cache and it seems to work OK, it changes the `/Account/Login?ReturnUrl` parameter so it's just got an `authzId` param on the `/connect/authorize/callback?authzId=`, which fixes the problem.

I think the base64 idea might be as simple as this:

```c#
public class Base64AuthorizationParametersMessageStore : IAuthorizationParametersMessageStore
{
    public Task<string> WriteAsync(Message<IDictionary<string, string[]>> message)
    {
        var json = ObjectSerializer.ToString(message);
        var bytes = Encoding.UTF8.GetBytes(json);
        var base64 = Base64Url.Encode(bytes);
        return Task.FromResult(base64);
    }

    public Task<Message<IDictionary<string, string[]>>> ReadAsync(string base64)
    {
        var bytes = Base64Url.Decode(base64);
        var json = Encoding.UTF8.GetString(bytes);
        var message = ObjectSerializer.FromString<Message<IDictionary<string, string[]>>>(json);
        return Task.FromResult(message);
    }

    public Task DeleteAsync(string id) => Task.CompletedTask;
}
```

**Comment by brockallen** [comment]
> I think the base64 idea might be as simple as this:

Oh yea, I bet it would be.... I hadn't thought thru it all. You can always try that and skip the cache. If you do, let us know how it goes.

**Comment by markrendle** [comment]
@brockallen Made a slight modification to use MessagePack (to minimize the size of the query parameter), and it seems to work. IS still calls it `authzId` but that's fine. Only concern is that there might be a ton of scopes or a long enough redirect_uri which could push the query parameter past a maximum size, but in that case you'd pretty much have to use a separate storage mechanism anyway.

Feel free to use this code if you want.

```c#
public class Base64AuthorizationParametersMessageStore : IAuthorizationParametersMessageStore
{
    private static readonly MessagePackSerializerOptions Options = MessagePackSerializerOptions.Standard;
    
    public Task<string> WriteAsync(Message<IDictionary<string, string[]>> message)
    {
        var packable = new PackableMessage
        {
            Created = message.Created,
            Data = message.Data,
        };
        var bytes = MessagePackSerializer.Serialize(packable, Options);
        var base64 = Base64Url.Encode(bytes);
        return Task.FromResult(base64);
    }

    public Task<Message<IDictionary<string, string[]>>> ReadAsync(string base64)
    {
        var bytes = Base64Url.Decode(base64);
        var packable = MessagePackSerializer.Deserialize<PackableMessage>(bytes, Options);
        var message = new Message<IDictionary<string, string[]>>
        {
            Created = packable.Created,
            Data = packable.Data
        };
        return Task.FromResult(message);
    }

    public Task DeleteAsync(string id) => Task.CompletedTask;

    [MessagePackObject]
    public class PackableMessage
    {
        [Key(0)]
        public long Created { get; set; }
        
        [Key(1)]
        public IDictionary<string, string[]> Data { get; set; }
    }
}
```
