### ISSUE TITLE
Update notes from 5.2 to 6.0 do not mention client secret length checks that are new

### ISSUE THREAD

**Issue by billpieper** [DuendeSoftware/IdentityServer#654]
We upgraded from v5.2 to 6.0 and ran into an issue where one of our client secrets was too long and our app started failing.

The upgrade notes should probably mention that there some new checks for length that were not present in the past version.

https://docs.duendesoftware.com/identityserver/v6/upgrades/v5.2_to_v6.0

**Comment by brockallen** [comment]
> We upgraded from v5.2 to 6.0 and ran into an issue where one of our client secrets was too long and our app started failing.

Umm... I don't recall us changing anything related to that. Were you seeing this on the token endpoint? How long was the secret? 

There is a `InputLengthRestrictions.ClientSecret` that defaults to 100 and it's been that way for years.

**Comment by brockallen** [comment]
Hi @billpieper. Do you have any info that can help shed some light on what happened here?

**Comment by billpieper** [comment]
We were running on 5.2.  Our client secret length had been 101 characters.  We never had an issue until we upgraded to 6.0.  At that time, IdentityServer started failing.  Our secrets and config had not changed.

The failing request was to /connect/token endpoint.
Source Context:  Duende.IdentityServer.Validation.BasicAuthenticationSecretParser
Log message:  Client secret exceeds maximum length.

We had not changed anything with configuration.  And prior to 6.0, we were not overriding any config values to override any defaults that would have impacted this.

**Comment by brockallen** [comment]
That's very bizarre. I'd love a repo from a working 5.2 if you had one handy?

**Comment by billpieper** [comment]
I don't have one running anymore -- we are fully upgraded to 6.0 now.

**Comment by brockallen** [comment]
Ok, I'll close this since I don't have a repo to take any action on. Glad you're all updated, though!
