### ISSUE TITLE
Proposal / Feature-Request: Include symbols and reference Microsoft.SourceLink.Github

### ISSUE THREAD

**Issue by alsami** [DuendeSoftware/IdentityServer#665]
**Which version of Duende IdentityServer are you using?**

6.0.1

**Which version of .NET are you using?**

6.0.1

**Describe the bug**

This is not really a bug, more of a proposal / feature-request. I would like to be able to better debug the Identity-Server sources. For that the symbols could be used when uploading the package and additionally [Microsoft.SourceLink.Github](https://www.nuget.org/packages/Microsoft.SourceLink.GitHub/) may be referenced.

**Additional context**

If you wish to do that I would be happy to send a PR your way.

**Comment by leastprivilege** [comment]
We embed the symbols. Should work.

**Comment by alsami** [comment]
Thanks for the quick reply. That's odd, here for instance the disassembled code of the default secret-validator:

![image](https://user-images.githubusercontent.com/2729205/150743967-0f670a8d-60a4-42ca-94d8-cea963feb534.png)

You can tell by the header of the file that Rider had to decompile the sources in order to show the code.
Is it possible that the reference needs to be included in `Directory.Build.props` rather than `Directory.Build.targets`?

**Comment by leastprivilege** [comment]
IIRC Rider has problems with embedded pdbs. I hope that will be fixed soon.

**Comment by leastprivilege** [comment]
Had a chat with JetBrains. Could you give the Rider nightly build (2021.3.3) a try. They say it should be fixed by now.

That would be good feedback! thanks!

**Comment by alsami** [comment]
Thanks again for the quick feedback.

There are indeed several tickets regarding that issue open at JetBrains Rider YouTrack.
Sadly, the latest EAP is not yet available on Linux with snap. 

I will check again in the next days and let you know once I am able to download it.

**Comment by alsami** [comment]
2021.3.3 has been released as a stable version and the problem is fixed. Thanks again!
