### ISSUE TITLE
Exception at Duende.IdentityServer.Stores.IResourceStoreExtensions.ValidateNameUniqueness with the Configuration Store Cache enabled

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/IdentityServer#684]
**Which version of Duende IdentityServer are you using?**

6.0.1 (but it also happens with the current version of the source code).

**Which version of .NET are you using?**

NET 6.

**Describe the bug**

`System.Exception at Duende.IdentityServer.Stores.IResourceStoreExtensions.ValidateNameUniqueness` when retrieving a token the second time (the first one works fine).

**To Reproduce**

1. Configure an API Scope, an API Resource and a Client as described below.
2. Retrieve a client credentials token for that client (no specific scopes requested).
3. It works fine.
3. Repeat.
4. It fails with the specified exception.

This also happens if you have another client that uses some of the same scopes as the first one.

If you do not enable the store cache (`AddConfigurationStoreCache()`), everything works fine.

**Expected behavior**

It should not raise any exception.

**Additional context**

There is something wrong in `CachingResourceStore<T>FindItemsAsync()`.

Here's the resources configuration:

API Scopes

- `identityserver4`
- `identityserver4-wh`
- `identityserver4-write`
- `lithium-notifications`
- `lithium-notifications-wh`
- `lithium-settings`

API Resources

- `identityserver4` (scopes: `identityserver4`, `identityserver4-wh`, `identityserver4-write`)
- `lithium-notifications` (scopes: `lithium-notifications`, `lithium-notifications-wh`)
- `lithium-settings` (scopes: `lithium-settings`)

Clients

- client1 (`client_credentials`) (scopes: `identityserver4`, `identityserver4-wh`, `identityserver4-write`, `lithium-notifications`, `lithium-notifications-wh`, `lithium-settings`)

**Comment by brockallen** [comment]
Can you provide the full call stack, please? Also, can you test if you get the exception from the discovery document as well?

**Comment by brockallen** [comment]
We have reproduced the issue, and will work on a fix. Thanks for reporting.

**Comment by brockallen** [comment]
We pushed a preview to [our MyGet feed](https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds) for 6.0.3-preview.1. Can you try it out and see if it addresses the issue?

**Comment by michaeldimoudis** [comment]
Can I confirm if this is a v6 only bug? We haven't updated from v5 yet and are about to turn on memory caching tomorrow. Our testing was all fine but just want to confirm we on v5 won't run into this issue in production. Thank you.

**Comment by brockallen** [comment]
Yes, this was a 6.0 only issue due to the reworking of the CachingResourceStore.

**Comment by hugoqribeiro** [comment]
> We pushed a preview to [our MyGet feed](https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds) for 6.0.3-preview.1. Can you try it out and see if it addresses the issue?

Hi. Yes it does.

**Comment by brockallen** [comment]
Great, thanks. We'll get a official patch out on NuGet soon.

**Comment by brockallen** [comment]
NuGet has been published: https://www.nuget.org/packages/Duende.IdentityServer/6.0.3
