### ISSUE TITLE
IssuerUri from appsettings.json is ignored

### ISSUE THREAD

**Issue by maubin-kl** [DuendeSoftware/IdentityServer#710]
**Which version of Duende IdentityServer are you using?**
6.0.4

**Which version of .NET are you using?**
.NET 6.0

**Describe the bug**
The IssuerUri from the appsettings.json is ignored. [As defined in the documentation](https://docs.duendesoftware.com/identityserver/v6/fundamentals/clients/#defining-clients-in-appsettingsjson)
The token I request still have the server address and not the IssuerUri from the config.

If I set the IssuerUri in the AddIdentityServer in the Startup.cs, my token now have the new IssuerUri.
`services.AddIdentityServer(options => options.IssuerUri = "http://something.com")`

**To Reproduce**

1. Create a new ASP.NET core application with Duende 6.0.4.
2. Set an IssuerUri in the appsettings.json
3. Generate a token and validate the IssuerUri in the token.

**Expected behavior**

I would expect the IssuerUri from the appsettings.json to be used when set.

**Comment by leastprivilege** [comment]
Thank! Yes the docs are misleading. 

We do not load the issuer URI automatically from the config file. You would need to do that yourself.
