### ISSUE TITLE
Change KeyManager "Active signing key" log to Debug

### ISSUE THREAD

**Issue by glucaci** [DuendeSoftware/IdentityServer#716]
I think [this](https://github.com/DuendeSoftware/IdentityServer/blob/ffa4da997b44dcb32103bb26a919fb14cd1cf0f5/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs#L79) log is to verbose for what information is providing.

Could we maybe change it to `Debug` and log `Information` only when `age` is below a certain value?

I could do a PR if we decide it's ok.

**Comment by brockallen** [comment]
I don't have an objection to that. @leastprivilege?

**Comment by leastprivilege** [comment]
Agreed

**Comment by brockallen** [comment]
I think this was fixed via: https://github.com/DuendeSoftware/IdentityServer/pull/834
