### ISSUE TITLE
Post-login redirect not working in Edge browser

### ISSUE THREAD

**Issue by EajksEajks** [DuendeSoftware/IdentityServer#80]
```
    <PackageReference Include="Duende.IdentityServer" Version="5.0.0" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="5.0.0" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="5.0.0" />

```
The post-login redirect doesn't work in Edge but works fine in Firefox.

I have an MVC redirecting me to the IdentityServer login page where I can enter the alice/Pass123$ test credentials. In the Firefox browser I am redirected back to the MVC while in the Edge browser I land again and again on the IdentityServer login page to enter my credentials.

If I directly login on the IdentityServer login page (instead of being redirected to it), it works fine. I enter the credentials once and can see the claim.

I have found in the internet many references to this issue in the past years, many related to CSP security, and I tried each of them but none of them solved my problem.

**Comment by brockallen** [comment]
We need to be able to reproduce what you're seeing, so given your description I suspect it's the ASP.NET Identity quickstart? I just tested it, and it seems to be working for me. Are you running the IIS express host, instead of the console host? They run on different ports, so perhaps that's why it's not working?

**Comment by EajksEajks** [comment]
I follow as much as I can the ASP.NET Identity quickstart with the notable exception that I only have http/80 access to the identity server instead of the https access you use.

**Comment by brockallen** [comment]
> while in the Edge browser I land again and again on the IdentityServer login page to enter my credentials.

Hmm, this feels like the correlation cookie in the client app is not persisting across the redirects. Likely due to the lack of HTTPS. Can you try with HTTPS? I suspect it will start to work then.

**Comment by EajksEajks** [comment]
You're right. It works when I switch to HTTPS.
But why does it work with Firefox/Chrome but not with Edge? Is there a workaround?

**Comment by brockallen** [comment]
> But why does it work with Firefox but not with Edge

This is due to the same-site cookie changes in recent years, and different browsers are evolving at a different pace. In short, we all should be using HTTPS always, even for local development.

**Comment by EajksEajks** [comment]
Okay I can understand. I would appreciate your opinion about how I should structure my microservice architecture given that they will be behind a nginx (or equiv) reverse proxy which will get rid of HTTPS. Won't the identity server respond to HTTP-only requests? Will it handle traffic form Firefox AND Edge correctly? If yes does it mean that for dev purpose I have to systematically debug my identity service together with the nginx reverse proxy?

Thanks for your help. I appreciate it.

**Comment by brockallen** [comment]
> how I should structure my microservice architecture given that they will be behind a nginx (or equiv) reverse proxy which will get rid of HTTPS

If the reverse proxy sends the right headers, and you add the *forwarded headers* middleware in your IdentityServer host, then all should be ok.

https://docs.duendesoftware.com/identityserver/v5/deployment/proxies/

**Comment by leastprivilege** [comment]
There has not been any activity recently. Is this issue resolved?

**Comment by EajksEajks** [comment]
Yes
    On Tuesday, February 23, 2021, 08:41:34 AM GMT+1, Dominick Baier <notifications@github.com> wrote:  
 
 


There has not been any activity recently. Is this issue resolved?
