### ISSUE TITLE
Contribution guidance

### ISSUE THREAD

**Issue by AliBazzi** [DuendeSoftware/IdentityServer#82]
Hi,

It's not a bug report really, but there was a contribution [section](https://identityserver4.readthedocs.io/en/latest/intro/contributing.html#contribution-projects) on IdentityServer4 that used to guide us on naming of third party packages, it's gone from Duende Identity Server docs.

Wandering what is the guidance here ? given I tried to upload a library for DynamoDB operational store on Nuget, but the last complained with:

```
This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.
```

**Comment by leastprivilege** [comment]
We will discuss this internally. Thanks!

**Comment by leastprivilege** [comment]
Hey, 

OK - we discussed this. Given that we are now a "real" company, it is a bit problematic to open up the NuGet namespace for arbitrary packages.

I would recommend you are hosting the package under your own name identity like

`YourName.DynamoDb.Duende` 

or similar...

We are happy to create a directory of 3rd party add-ons in our documentation, so they are easier to discover. So please send us the link to your documentation/website when you are ready.

OK?

**Comment by AliBazzi** [comment]
Hi,

sounds good, thanks for the update.
