### ISSUE TITLE
Consider improving key management error messages

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#851]
to point to common problems?

https://github.com/DuendeSoftware/IdentityServer/discussions/850

**Comment by juhariihela2** [comment]
We have same issue and errors in log, Anders help we to migrate old version 2.5.2 to 6.0.4 and to new NET6 framework couple of months ago. Now need to solve this session cookie problem. In 850 issue read "it's important that you configure data protection properly" and just like to know, how to do this correctly? We don't have this EF database here, we use custom Cosmos DB database to save users.

**Comment by brockallen** [comment]
@juhariihela2 We document that it's needed for deployments [here](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/). But it's not an IdentityServer feature -- it's an ASP.NET Core feature, so you must read the Microsoft documentation to best answer those questions for your environment.
