### ISSUE TITLE
Re-visit JAR and OIDC RO spec and validate against our implementation

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#9]
https://darutk.medium.com/implementers-note-about-jar-fff4cbd158fe

**Comment by leastprivilege** [comment]
Once the final JAR spec is out, we probably need to introduce a per client switch to control the OIDC RO vs JAR behavior (sigh b/c incompatible).

**Comment by leastprivilege** [comment]
JAR is final now.

Will re-visit this for after the 5.2 release

**Comment by leastprivilege** [comment]
https://datatracker.ietf.org/doc/html/rfc9101

**Comment by leastprivilege** [comment]
It seems we satisfy both by

* always require `client_id` outside the RO
* if any other parameter is present outside the RO - it must be mirrored inside the RO with the same value

**Comment by brockallen** [comment]
I had a look and I think we do the best we can to juggle the difference between OAuth and OIDC request object.

The one thing not mentioned above is that OIDC allow some params to be outside the request object, whereas the OAuth spec seems to imply that all params (except for client id and the request object) must be inside the request object. We follow the OIDC approach.

@leastprivilege anything else we want to do here?

**Comment by brockallen** [comment]
Ok, then we're all set here in how we do things.
