### ISSUE TITLE
Setting ClientClaimsPrefix-property to a whitespace in appsetting.json

### ISSUE THREAD

**Issue by thomasduft** [DuendeSoftware/IdentityServer#91]
Used version:
```xml
<PackageReference Include="Duende.IdentityServer" Version="5.0.1" />
```

Configuring a "client credentials" client within the appsettings.json file like the following

```json
...
  "AllowedScopes": [
    "demo_api",
  ],
  "ClientClaimsPrefix": "",
  "Claims": [
    {
      "Type": "role",
      "Value": "some_role"
    }
  ]
...
```

will end with the client claim prefix "client_" within the `role`-claim in the token ("client_role": "some_role").

If the goal is to have set the `role`-claimtype set to "role": "some_role" you will need to explicitly set the value to a **whitespace** like this:

```json
...
  "AllowedScopes": [
    "demo_api",
  ],
  "ClientClaimsPrefix": " ",
  "Claims": [
    {
      "Type": "role",
      "Value": "some_role"
    }
  ]
...
```

Then the client claim prefix "client_" within the issued token disappears.

The [docs](https://docs.duendesoftware.com/identityserver/v5/fundamentals/claims/) says that when setting the `ClientClaimsPrefix`-property the set value will have effect. 

However, it kind of feels like a bug when configuring a client via the appsettings and using a whitespace. This seems a bit odd and probably some kind like a `UseClientClaimsPrefix`-property would make more sense when configuring a client in the appsettings.

**Comment by brockallen** [comment]
For that mapping, we just use the built in `Bind` feature from ASP.NET Core. I suspect this is how the appsettings mapping works if the value is an empty string -- meaning, they ignore it. We'll see if we can repro on our end.

**Comment by brockallen** [comment]
Hmm, I just tested this with our host that we use for dev/testing and it seems to work the way you want. In other words, I set:

```
  "Clients": [
    {
      "ClientId": "test",
      "ClientClaimsPrefix": "",
      "Claims": [
        {
          "type": "c1",
          "value": "c1value"
        },
        {
          "type": "c2",
          "value": "c2value"
        }
      ],
       ...
      }
]
```

And the loaded prefix is the empty string:

```
Access Token (decoded):
{
  "alg": "RS256",
  "kid": "35924301E3F6857DDC944654772E11B5",
  "typ": "at\u002Bjwt"
}
{
  "iss": "https://localhost:5001",
  "nbf": 1611698528,
  "iat": 1611698528,
  "exp": 1611702128,
  "aud": "urn:resource1",
  "scope": "resource1.scope1 resource1.scope2",
  "client_id": "client",
  "c1": "c1value",
  "c2": "c2value",
  "jti": "3E2E20D182D5F5849E1A73B5799ABC3E"
}
```

So, I'd ask if you can try to use the same test host and see if you get the same results.

**Comment by leastprivilege** [comment]
Also - are you using .NET Core 3.1 or .NET 5 ?

**Comment by thomasduft** [comment]
Hi there

Thanks so far. Because .net5.0 is not an LTS version we are building our stuff still on .NET 3.1.

@brockallen : Tomorrow I will retry it for both .net5.0 and netcoreapp3.1 and let you know.

Another solution I could implement is a custom `ICustomTokenRequestValidator` that takes care of our use case in order not to confuse our customers when configuring their environment via the appconfig.json approach.

Thanks again and have a great day

Thomas

**Comment by thomasduft** [comment]
Ok as I promised here my results:

**Test setup: 1**
Env: netcoreapp3.1
ClientClaimsPrefix: "" // empty string
JWT-Payload:
```json
{
  "iss": "https://localhost:12300",
  "nbf": 1611617539,
  "iat": 1611617539,
  "exp": 1611621139,
  "scope": [
    "cs_api",
    "mb_api",
    "rs_api",
    "ts_api"
  ],
  "client_id": "mercury.client",
  "client_role": "mercury",
  "jti": "C94231D3CA6DBBBA3C01F2BBEAC7EEEE"
}
```

**Test setup: 2**
Env: netcoreapp3.1
ClientClaimsPrefix: " " // whitespace
JWT-Payload:
```json
{
  "iss": "https://localhost:12300",
  "nbf": 1611817355,
  "iat": 1611817355,
  "exp": 1611820955,
  "scope": [
    "cs_api",
    "mb_api",
    "rs_api",
    "ts_api"
  ],
  "client_id": "mercury.client",
  "role": "mercury",
  "jti": "DEEC8DD84CE34D61705604E752EC4563"
}
```

**Test setup: 3**
Env: net5.0
ClientClaimsPrefix: "" // empty string
JWT-Payload:
```json
{
  "iss": "https://localhost:12300",
  "nbf": 1611817615,
  "iat": 1611817615,
  "exp": 1611821215,
  "scope": [
    "cs_api",
    "mb_api",
    "rs_api",
    "ts_api"
  ],
  "client_id": "mercury.client",
  "client_role": "mercury",
  "jti": "EED5F8BA61A46AF9E0FF8A4C40AF7A97"
}
```

**Test setup: 4**
Env: net5.0
ClientClaimsPrefix: " " // whitespace
JWT-Payload:
```json
{
  "iss": "https://localhost:12300",
  "nbf": 1611817716,
  "iat": 1611817716,
  "exp": 1611821316,
  "scope": [
    "cs_api",
    "mb_api",
    "rs_api",
    "ts_api"
  ],
  "client_id": "mercury.client",
  "role": "mercury",
  "jti": "EB721F1179555C793B3633D71436CC09"
}
```

As you can see it does not matter whether you use .NET Core 3.1 or .NET 5. Our goal is to have the result of the test setup 2 and 4 which means the `role`-claimtype must be **role** and not **client_role**.  

As I mentioned configuring the `ClientClaimsPrefix` in the appsettings.json with an whitespace in order to get the `role`-claimtype to be without the `client_`-prefix is odd. Therefore I am now going to implement a custom `ICustomTokenRequestValidator` in order not to confuse our customers during commissioning.

I am closing this issue because it seems an underlying problem of the .NET `Bind`-feature. In case you will have similar issues at least you are now aware of it.

Thomas

**Comment by leastprivilege** [comment]
We will investigate...

**Comment by leastprivilege** [comment]
We just tried it again in a stand-alone app - and can't repro. weird.

Closing for now...
