### ISSUE TITLE
Consider: Improve issuer validation error message

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#918]
Currently it says

> Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2.

This seems to happen a lot with gateway/proxy/container scenarios - Maybe add information about setting a static issuerUri.

**Comment by brockallen** [comment]
Possible message: "This might be due to your server being accessed via different URLs or a direct IP and/or you have reverse proxy or a gateway involved. This suggests a network infrastructure configuration problem."
