### ISSUE TITLE
Customize Login page

### ISSUE THREAD

**Issue by MikeOtown** [DuendeSoftware/IdentityServer#948]
I'm starting with one of the Template Applications and having a hard time customizing the Login page.  My /Pages/Account/Login/Index.cshtml isn't getting rendered.  Instead, this is rendered:

![image](https://user-images.githubusercontent.com/18534728/175992605-2c1840ef-29f4-4c10-8a8d-9fe935927fcf.png)

How can I customize the Login UI?

**Comment by brockallen** [comment]
Closing, dup of: https://github.com/DuendeSoftware/Support/issues/104
