### ISSUE TITLE
Consider how to allow delay for deleting consumed grants

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#982]
https://github.com/DuendeSoftware/Support/issues/54

Maybe related: https://github.com/DuendeSoftware/IdentityServer/issues/981

> The `RemoveConsumedTokens` property was added in [DuendeSoftware/IdentityServer#84](https://github.com/DuendeSoftware/IdentityServer/pull/84) which works well. But it does cause a side effect when enabled:
> 
> If we had implemented a "grace period" logic via a custom `IRefreshTokenService` to mitigate transient issues related to consumed one-time refresh tokens and public clients with unstable network conditions, the logic would require that the consumed tokens still exist in the datastore for the duration of the grace period. Auto cleanup would remove these tokens on each run.
> 
> In this case, it would be nice if we can specify an option to only auto remove consumed tokens older than X (a `TimeSpan`). This will allow auto cleanup to function without affecting the aforementioned custom logic.
> 
> Because the token cleanup service is non-extensible, exposing such an option via `OperationStoreOptions` and using it in `RemoveConsumedPersistedGrantsAsync` would be the best way to go.

**Comment by josephdecock** [comment]
This is implemented in #1105.
